#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from limbaj.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "limbaj.y"

#include <iostream>
#include <vector>
#include "SymTable.h"
#include "AST.h"
extern FILE* yyin;
extern char* yytext;
extern int yylineno;
extern int yylex();
void yyerror(const char * s);
class SymTable* current;
vector<SymTable*> tables;

int errorCount = 0;

#line 16 "limbaj.y"
typedef union 
{
     int number;
     float real_number;
     bool true_or_false;
     char caracter;
     char* string;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	BGIN	258
#define	END	259
#define	ASSIGN	260
#define	NR	261
#define	BGINGLOBAL	262
#define	ENDGLOBAL	263
#define	BGINVARS	264
#define	ENDVARS	265
#define	BGINCLASS	266
#define	ENDCLASS	267
#define	BGINFUNC	268
#define	ENDFUNC	269
#define	CLASS	270
#define	CONST	271
#define	EQ	272
#define	NEQ	273
#define	GT	274
#define	LT	275
#define	GTE	276
#define	LTE	277
#define	AND	278
#define	OR	279
#define	NOT	280
#define	PRINT	281
#define	TYPEOF	282
#define	EVAL	283
#define	IF	284
#define	ELSE	285
#define	WHILE	286
#define	FOR	287
#define	DO	288
#define	LOOP	289
#define	BREAK	290
#define	CONTINUE	291
#define	RETURN	292
#define	ID	293
#define	TYPE	294
#define	STRING	295
#define	CHAR	296
#define	FLOAT	297
#define	INT	298
#define	BOOL	299


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int BGIN;
static const int END;
static const int ASSIGN;
static const int NR;
static const int BGINGLOBAL;
static const int ENDGLOBAL;
static const int BGINVARS;
static const int ENDVARS;
static const int BGINCLASS;
static const int ENDCLASS;
static const int BGINFUNC;
static const int ENDFUNC;
static const int CLASS;
static const int CONST;
static const int EQ;
static const int NEQ;
static const int GT;
static const int LT;
static const int GTE;
static const int LTE;
static const int AND;
static const int OR;
static const int NOT;
static const int PRINT;
static const int TYPEOF;
static const int EVAL;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int DO;
static const int LOOP;
static const int BREAK;
static const int CONTINUE;
static const int RETURN;
static const int ID;
static const int TYPE;
static const int STRING;
static const int CHAR;
static const int FLOAT;
static const int INT;
static const int BOOL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,BGIN=258
	,END=259
	,ASSIGN=260
	,NR=261
	,BGINGLOBAL=262
	,ENDGLOBAL=263
	,BGINVARS=264
	,ENDVARS=265
	,BGINCLASS=266
	,ENDCLASS=267
	,BGINFUNC=268
	,ENDFUNC=269
	,CLASS=270
	,CONST=271
	,EQ=272
	,NEQ=273
	,GT=274
	,LT=275
	,GTE=276
	,LTE=277
	,AND=278
	,OR=279
	,NOT=280
	,PRINT=281
	,TYPEOF=282
	,EVAL=283
	,IF=284
	,ELSE=285
	,WHILE=286
	,FOR=287
	,DO=288
	,LOOP=289
	,BREAK=290
	,CONTINUE=291
	,RETURN=292
	,ID=293
	,TYPE=294
	,STRING=295
	,CHAR=296
	,FLOAT=297
	,INT=298
	,BOOL=299


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::BGIN=258;
const int YY_parse_CLASS::END=259;
const int YY_parse_CLASS::ASSIGN=260;
const int YY_parse_CLASS::NR=261;
const int YY_parse_CLASS::BGINGLOBAL=262;
const int YY_parse_CLASS::ENDGLOBAL=263;
const int YY_parse_CLASS::BGINVARS=264;
const int YY_parse_CLASS::ENDVARS=265;
const int YY_parse_CLASS::BGINCLASS=266;
const int YY_parse_CLASS::ENDCLASS=267;
const int YY_parse_CLASS::BGINFUNC=268;
const int YY_parse_CLASS::ENDFUNC=269;
const int YY_parse_CLASS::CLASS=270;
const int YY_parse_CLASS::CONST=271;
const int YY_parse_CLASS::EQ=272;
const int YY_parse_CLASS::NEQ=273;
const int YY_parse_CLASS::GT=274;
const int YY_parse_CLASS::LT=275;
const int YY_parse_CLASS::GTE=276;
const int YY_parse_CLASS::LTE=277;
const int YY_parse_CLASS::AND=278;
const int YY_parse_CLASS::OR=279;
const int YY_parse_CLASS::NOT=280;
const int YY_parse_CLASS::PRINT=281;
const int YY_parse_CLASS::TYPEOF=282;
const int YY_parse_CLASS::EVAL=283;
const int YY_parse_CLASS::IF=284;
const int YY_parse_CLASS::ELSE=285;
const int YY_parse_CLASS::WHILE=286;
const int YY_parse_CLASS::FOR=287;
const int YY_parse_CLASS::DO=288;
const int YY_parse_CLASS::LOOP=289;
const int YY_parse_CLASS::BREAK=290;
const int YY_parse_CLASS::CONTINUE=291;
const int YY_parse_CLASS::RETURN=292;
const int YY_parse_CLASS::ID=293;
const int YY_parse_CLASS::TYPE=294;
const int YY_parse_CLASS::STRING=295;
const int YY_parse_CLASS::CHAR=296;
const int YY_parse_CLASS::FLOAT=297;
const int YY_parse_CLASS::INT=298;
const int YY_parse_CLASS::BOOL=299;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		263
#define	YYFLAG		-32768
#define	YYNTBASE	61

#define YYTRANSLATE(x) ((unsigned)(x) <= 299 ? yytranslate[x] : 92)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    49,     2,     2,    53,
    54,    47,    45,    59,    46,    60,    48,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    58,    55,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    51,     2,    52,    50,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    56,     2,    57,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     7,     8,    12,    16,    17,    20,    24,    27,
    33,    37,    38,    40,    43,    51,    53,    56,    61,    64,
    65,    66,    76,    80,    81,    83,    86,    87,    97,   104,
   106,   110,   111,   114,   118,   120,   124,   125,   129,   132,
   136,   138,   140,   143,   149,   157,   169,   177,   186,   191,
   203,   205,   207,   209,   212,   217,   223,   228,   232,   236,
   243,   250,   256,   261,   265,   270,   275,   279,   286,   288,
   293,   299,   303,   309,   313,   319,   323,   329,   333,   339,
   343,   349,   353,   359,   363,   369,   373,   378,   380,   383,
   385,   389,   393,   397,   401,   405,   409,   412,   414,   416,
   418,   420,   425,   429,   433
};

static const short yyrhs[] = {    62,
    83,     0,     7,    63,     8,     0,     0,    64,    67,    75,
     0,     9,    65,    10,     0,     0,    66,    55,     0,    65,
    66,    55,     0,    39,    38,     0,    39,    38,    51,    81,
    52,     0,    11,    68,    12,     0,     0,    69,     0,    68,
    69,     0,    15,    38,    56,    70,    72,    57,    55,     0,
    71,     0,    70,    71,     0,    38,    58,    39,    55,     0,
    72,    73,     0,     0,     0,    39,    38,    53,    79,    54,
    56,    74,    82,    57,     0,    13,    76,    14,     0,     0,
    77,     0,    76,    77,     0,     0,    39,    38,    53,    79,
    54,    56,    78,    82,    57,     0,    39,    38,    53,    79,
    54,    55,     0,    80,     0,    79,    59,    80,     0,     0,
    39,    38,     0,    81,    59,    43,     0,    43,     0,    82,
    85,    55,     0,     0,     3,    84,     4,     0,    85,    55,
     0,    84,    85,    55,     0,    88,     0,    66,     0,    38,
    38,     0,    38,    38,    56,    86,    57,     0,    29,    53,
    90,    54,    56,    84,    57,     0,    29,    53,    90,    54,
    56,    84,    57,    30,    56,    84,    57,     0,    31,    53,
    90,    54,    56,    84,    57,     0,    33,    56,    84,    57,
    31,    53,    90,    54,     0,    34,    56,    84,    57,     0,
    32,    53,    87,    55,    90,    55,    87,    54,    56,    84,
    57,     0,    87,     0,    36,     0,    35,     0,    37,    90,
     0,    38,     5,    91,    55,     0,    86,    38,     5,    91,
    55,     0,    39,    38,     5,    91,     0,    38,     5,    91,
     0,    38,     5,    40,     0,    38,    51,    81,    52,     5,
    91,     0,    38,    51,    81,    52,     5,    88,     0,    38,
    60,    38,     5,    91,     0,    38,    53,    89,    54,     0,
    38,    53,    54,     0,    26,    53,    40,    54,     0,    27,
    53,    38,    54,     0,    89,    59,    91,     0,    89,    59,
    38,    53,    89,    54,     0,    91,     0,    38,    53,    89,
    54,     0,    53,    90,    18,    90,    54,     0,    90,    18,
    90,     0,    53,    90,    17,    90,    54,     0,    90,    17,
    90,     0,    53,    90,    20,    90,    54,     0,    90,    20,
    90,     0,    53,    90,    22,    90,    54,     0,    90,    22,
    90,     0,    53,    90,    19,    90,    54,     0,    90,    19,
    90,     0,    53,    90,    21,    90,    54,     0,    90,    21,
    90,     0,    53,    90,    23,    90,    54,     0,    90,    23,
    90,     0,    53,    90,    24,    90,    54,     0,    90,    24,
    90,     0,    53,    25,    90,    54,     0,    44,     0,    25,
    90,     0,    91,     0,    91,    45,    91,     0,    91,    47,
    91,     0,    91,    48,    91,     0,    91,    46,    91,     0,
    91,    49,    91,     0,    53,    91,    54,     0,    46,    91,
     0,    38,     0,    43,     0,    42,     0,    41,     0,    38,
    51,    81,    52,     0,    38,    60,    38,     0,    38,    60,
    88,     0,    88,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    45,    52,    53,    57,    61,    62,    66,    67,    72,    80,
    90,    91,    94,    95,    99,   103,   104,   108,   112,   113,
   117,   119,   126,   127,   131,   132,   136,   138,   142,   145,
   146,   147,   150,   154,   155,   159,   160,   164,   167,   168,
   172,   173,   174,   175,   176,   177,   178,   179,   180,   181,
   182,   183,   184,   185,   188,   189,   192,   193,   194,   195,
   196,   197,   201,   202,   203,   204,   208,   209,   210,   211,
   215,   216,   217,   218,   219,   220,   221,   222,   223,   224,
   225,   226,   227,   228,   229,   230,   231,   232,   233,   234,
   238,   239,   240,   241,   242,   243,   244,   245,   246,   247,
   248,   249,   250,   251,   252
};

static const char * const yytname[] = {   "$","error","$illegal.","BGIN","END",
"ASSIGN","NR","BGINGLOBAL","ENDGLOBAL","BGINVARS","ENDVARS","BGINCLASS","ENDCLASS",
"BGINFUNC","ENDFUNC","CLASS","CONST","EQ","NEQ","GT","LT","GTE","LTE","AND",
"OR","NOT","PRINT","TYPEOF","EVAL","IF","ELSE","WHILE","FOR","DO","LOOP","BREAK",
"CONTINUE","RETURN","ID","TYPE","STRING","CHAR","FLOAT","INT","BOOL","'+'","'-'",
"'*'","'/'","'%'","'^'","'['","']'","'('","')'","';'","'{'","'}'","':'","','",
"'.'","progr","global_declarations","declarations","vars_declarations","decl_vars",
"decl_var","class_declarations","decl_classes","decl_class","membs_list","class_memb",
"methods_list","method","@1","func_declarations","decl_funcs","def_func","@2",
"list_param","param","list_array","fblock","main","list","statement","init_instante",
"assignment_stmt","call_func","call_list","bool_expr","arithm_expr",""
};
#endif

static const short yyr1[] = {     0,
    61,    62,    62,    63,    64,    64,    65,    65,    66,    66,
    67,    67,    68,    68,    69,    70,    70,    71,    72,    72,
    74,    73,    75,    75,    76,    76,    78,    77,    77,    79,
    79,    79,    80,    81,    81,    82,    82,    83,    84,    84,
    85,    85,    85,    85,    85,    85,    85,    85,    85,    85,
    85,    85,    85,    85,    86,    86,    87,    87,    87,    87,
    87,    87,    88,    88,    88,    88,    89,    89,    89,    89,
    90,    90,    90,    90,    90,    90,    90,    90,    90,    90,
    90,    90,    90,    90,    90,    90,    90,    90,    90,    90,
    91,    91,    91,    91,    91,    91,    91,    91,    91,    91,
    91,    91,    91,    91,    91
};

static const short yyr2[] = {     0,
     2,     3,     0,     3,     3,     0,     2,     3,     2,     5,
     3,     0,     1,     2,     7,     1,     2,     4,     2,     0,
     0,     9,     3,     0,     1,     2,     0,     9,     6,     1,
     3,     0,     2,     3,     1,     3,     0,     3,     2,     3,
     1,     1,     2,     5,     7,    11,     7,     8,     4,    11,
     1,     1,     1,     2,     4,     5,     4,     3,     3,     6,
     6,     5,     4,     3,     4,     4,     3,     6,     1,     4,
     5,     3,     5,     3,     5,     3,     5,     3,     5,     3,
     5,     3,     5,     3,     5,     3,     4,     1,     2,     1,
     3,     3,     3,     3,     3,     3,     2,     1,     1,     1,
     1,     4,     3,     3,     1
};

static const short yydefact[] = {     3,
     6,     0,     0,     0,    12,     0,     1,     0,     0,     0,
     2,     0,    24,     0,     0,     0,     0,     0,     0,     0,
    53,    52,     0,     0,     0,    42,     0,     0,    51,    41,
     9,     5,     0,     7,     0,     0,    13,     0,     4,     0,
     0,     0,     0,     0,     0,     0,     0,    98,   101,   100,
    99,    88,     0,     0,   105,    54,    90,     0,    43,     0,
     0,     0,     9,    38,     0,    39,     0,     8,     0,    11,
    14,     0,     0,    25,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    89,     0,     0,     0,    97,     0,     0,
    90,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    59,    58,     0,    35,     0,    98,
    64,     0,    69,     0,     0,    40,     0,     0,     0,    23,
    26,    65,    66,     0,     0,     0,     0,     0,    49,     0,
   103,   104,     0,    89,     0,     0,     0,     0,     0,     0,
     0,     0,    96,    74,    72,    80,    76,    82,    78,    84,
    86,    91,    94,    92,    93,    95,     0,     0,     0,     0,
     0,    63,     0,     0,    57,    10,     0,    20,    16,    32,
     0,     0,     0,     0,   102,    87,    74,    72,    80,    76,
    82,    78,    84,    86,     0,     0,    44,     0,    34,     0,
    98,    67,    62,     0,    17,     0,     0,     0,    30,     0,
     0,     0,     0,    73,    71,    79,    75,    81,    77,    83,
    85,     0,     0,   105,    60,    63,     0,     0,     0,     0,
    19,    33,     0,     0,    45,    47,     0,     0,    55,     0,
     0,    18,     0,    15,    29,    27,    31,     0,     0,    48,
    56,    63,    32,    37,     0,     0,     0,     0,     0,     0,
     0,    28,     0,    46,    50,    21,    36,    37,     0,    22,
     0,     0,     0
};

static const short yydefgoto[] = {   261,
     2,     4,     5,     9,    26,    13,    36,    37,   168,   169,
   196,   221,   258,    39,    73,    74,   244,   198,   199,   109,
   248,     7,    27,    28,   158,    29,    55,   112,    56,    57
};

static const short yypact[] = {    37,
    55,    91,    69,   105,    99,   447,-32768,   121,    -3,    82,
-32768,   152,   158,   120,   139,   140,   177,   178,   181,   182,
-32768,-32768,   363,     8,   196,-32768,   228,   122,-32768,-32768,
   185,-32768,   201,-32768,   212,    33,-32768,   219,-32768,   211,
   232,   363,   363,   -19,   447,   447,   363,   -10,-32768,-32768,
-32768,-32768,   415,   385,-32768,   470,   465,   394,   216,   241,
    63,   248,    12,-32768,   246,-32768,   241,-32768,   240,-32768,
-32768,   277,    -4,-32768,   276,   290,    64,   102,     9,   287,
   299,   242,   256,-32768,   241,   123,   415,   172,   363,   478,
   106,   363,   363,   363,   363,   363,   363,   363,   363,   415,
   415,   415,   415,   415,-32768,   465,   321,-32768,   -44,    80,
-32768,   -12,   465,   368,   415,-32768,    43,   345,   331,-32768,
-32768,-32768,-32768,   335,   341,   380,   363,   356,-32768,    75,
   346,-32768,   106,   344,   363,   363,   363,   363,   363,   363,
   363,   363,-32768,   226,   226,-32768,-32768,-32768,-32768,   179,
   486,   172,   172,-32768,-32768,-32768,   398,   -20,   403,   370,
    63,-32768,   424,   415,   465,-32768,   357,   345,-32768,   375,
   447,   447,    10,   364,-32768,-32768,     4,    78,   365,   371,
   376,   379,    53,   195,   415,   413,-32768,   415,-32768,    76,
   119,   465,   465,   383,-32768,    54,   386,   103,-32768,   271,
   285,   -19,   363,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   180,   415,    24,   465,-32768,    63,   384,   405,   389,
-32768,-32768,   125,   375,   416,-32768,   391,   187,-32768,   347,
   104,-32768,   395,-32768,-32768,-32768,-32768,   393,   396,-32768,
-32768,-32768,   375,-32768,   447,   447,   124,   300,   314,   329,
   399,-32768,   404,-32768,-32768,-32768,-32768,-32768,   343,-32768,
   454,   460,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,-32768,    13,-32768,-32768,   427,-32768,   296,
-32768,-32768,-32768,-32768,-32768,   402,-32768,   229,   245,   -18,
   213,-32768,   -43,   -26,-32768,   -33,    -6,  -155,    49,   -49
};


#define	YYLAST		514


static const short yytable[] = {    30,
    65,    82,    83,    88,    91,   190,    32,   159,   106,   120,
    81,   113,    58,    58,   160,    10,   115,   186,    79,    80,
    30,    33,    94,    95,    96,    97,    92,    93,    94,    95,
    96,    97,    98,    99,    72,     8,   187,   133,    30,    30,
    85,   162,    61,     1,    70,    59,   163,    35,   117,    86,
   152,   153,   154,   155,   156,    65,    65,   204,    60,    60,
    61,   231,    67,     3,   202,   165,   130,    62,    62,    92,
    93,    94,    95,    96,    97,    30,    30,   -61,   -61,   132,
    92,    93,    94,    95,    96,    97,    98,    99,    14,    15,
    77,    78,   219,     6,   166,    84,    94,    95,    96,    97,
   110,   160,    90,    49,    50,    51,   210,     8,    53,    12,
   220,   113,    11,   192,   193,    87,   111,   124,    92,    93,
    94,    95,    96,    97,    98,    99,   175,   200,   201,   216,
    85,   205,   161,   160,   163,   212,    34,   134,   215,    86,
   144,   145,   146,   147,   148,   149,   150,   151,    14,    15,
   100,   101,   102,   103,   104,   125,   223,   242,    31,   143,
   131,   224,   163,   230,    30,    30,    35,   113,   227,    85,
    38,   217,    40,    65,    65,   173,    66,   251,    86,   235,
   236,   214,   224,   177,   178,   179,   180,   181,   182,   183,
   184,    41,    42,    30,    30,    92,    93,    94,    95,    96,
    97,   249,   250,    92,    93,    94,    95,    96,    97,    98,
    99,    92,    93,    94,    95,    96,    97,    98,   102,   103,
   104,   253,    65,    65,   100,   101,   102,   103,   104,    43,
    44,    64,   253,    63,   229,    67,    45,    46,    30,    30,
   240,    30,    30,    30,    94,    95,    96,    97,   211,    69,
    75,   228,    30,    14,    15,    68,    16,    72,    17,    18,
    19,    20,    21,    22,    23,    24,    25,    14,    15,    76,
    16,   107,    17,    18,    19,    20,    21,    22,    23,    24,
    25,    14,    15,   108,    16,   114,    17,    18,    19,    20,
    21,    22,    23,    24,    25,   118,    14,    15,   128,    16,
   116,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    14,    15,   129,    16,   119,    17,    18,    19,    20,    21,
    22,    23,    24,    25,   126,    14,    15,   225,    16,   122,
    17,    18,    19,    20,    21,    22,    23,    24,    25,    14,
    15,   226,    16,   123,    17,    18,    19,    20,    21,    22,
    23,    24,    25,   127,    14,    15,   252,    16,   157,    17,
    18,    19,    20,    21,    22,    23,    24,    25,    14,    15,
   254,    16,   164,    17,    18,    19,    20,    21,    22,    23,
    24,    25,   167,   170,   115,   255,   174,    47,    14,    15,
   171,   100,   101,   102,   103,   104,   172,   176,    61,   260,
    48,   241,   185,    49,    50,    51,    52,   188,    53,    89,
    14,    15,   189,   197,   194,    54,   203,   213,   206,    14,
    15,   218,    48,   222,   207,    49,    50,    51,    52,   208,
    53,    48,   209,   105,    49,    50,    51,    54,   232,    53,
    14,    15,   233,   234,   239,   238,    87,   243,   245,    14,
    15,   246,    48,   262,   256,    49,    50,    51,   257,   263,
    53,   191,    71,   195,    49,    50,    51,    87,   237,    53,
   259,   247,    14,    15,   121,    16,    87,    17,    18,    19,
    20,    21,    22,    23,    24,    25,    92,    93,    94,    95,
    96,    97,    98,    99,   135,   136,   137,   138,   139,   140,
   141,   142,    92,    93,    94,    95,    96,    97,    98,   100,
   101,   102,   103,   104
};

static const short yycheck[] = {     6,
    27,    45,    46,    53,    54,   161,    10,    52,    58,    14,
    44,    61,     5,     5,    59,     3,     5,    38,    38,    39,
    27,     9,    19,    20,    21,    22,    17,    18,    19,    20,
    21,    22,    23,    24,    39,    39,    57,    87,    45,    46,
    51,    54,    53,     7,    12,    38,    59,    15,    67,    60,
   100,   101,   102,   103,   104,    82,    83,    54,    51,    51,
    53,   217,    51,     9,    55,   115,    85,    60,    60,    17,
    18,    19,    20,    21,    22,    82,    83,    54,    55,    86,
    17,    18,    19,    20,    21,    22,    23,    24,    26,    27,
    42,    43,    39,     3,    52,    47,    19,    20,    21,    22,
    38,    59,    54,    41,    42,    43,    54,    39,    46,    11,
    57,   161,     8,   163,   164,    53,    54,    54,    17,    18,
    19,    20,    21,    22,    23,    24,    52,   171,   172,    54,
    51,    54,    53,    59,    59,   185,    55,    89,   188,    60,
    92,    93,    94,    95,    96,    97,    98,    99,    26,    27,
    45,    46,    47,    48,    49,    54,    54,    54,    38,    54,
    38,    59,    59,   213,   171,   172,    15,   217,   202,    51,
    13,    53,    53,   200,   201,   127,    55,    54,    60,    55,
    56,   188,    59,   135,   136,   137,   138,   139,   140,   141,
   142,    53,    53,   200,   201,    17,    18,    19,    20,    21,
    22,   245,   246,    17,    18,    19,    20,    21,    22,    23,
    24,    17,    18,    19,    20,    21,    22,    23,    47,    48,
    49,   248,   249,   250,    45,    46,    47,    48,    49,    53,
    53,     4,   259,    38,    55,    51,    56,    56,   245,   246,
    54,   248,   249,   250,    19,    20,    21,    22,    54,    38,
    40,   203,   259,    26,    27,    55,    29,    39,    31,    32,
    33,    34,    35,    36,    37,    38,    39,    26,    27,    38,
    29,    56,    31,    32,    33,    34,    35,    36,    37,    38,
    39,    26,    27,    43,    29,    38,    31,    32,    33,    34,
    35,    36,    37,    38,    39,    56,    26,    27,    57,    29,
    55,    31,    32,    33,    34,    35,    36,    37,    38,    39,
    26,    27,    57,    29,    38,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    38,    26,    27,    57,    29,    54,
    31,    32,    33,    34,    35,    36,    37,    38,    39,    26,
    27,    57,    29,    54,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    55,    26,    27,    57,    29,    38,    31,
    32,    33,    34,    35,    36,    37,    38,    39,    26,    27,
    57,    29,     5,    31,    32,    33,    34,    35,    36,    37,
    38,    39,    38,    53,     5,    57,    31,    25,    26,    27,
    56,    45,    46,    47,    48,    49,    56,    54,    53,    57,
    38,    55,     5,    41,    42,    43,    44,     5,    46,    25,
    26,    27,    43,    39,    58,    53,    53,     5,    54,    26,
    27,    39,    38,    38,    54,    41,    42,    43,    44,    54,
    46,    38,    54,    40,    41,    42,    43,    53,    55,    46,
    26,    27,    38,    55,    54,    30,    53,    53,    56,    26,
    27,    56,    38,     0,    56,    41,    42,    43,    55,     0,
    46,    38,    36,   168,    41,    42,    43,    53,   224,    46,
   258,   243,    26,    27,    73,    29,    53,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    17,    18,    19,    20,
    21,    22,    23,    24,    17,    18,    19,    20,    21,    22,
    23,    24,    17,    18,    19,    20,    21,    22,    23,    45,
    46,    47,    48,    49
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 45 "limbaj.y"
{ 
                                   if (errorCount == 0) 
                                       std::cout << "The program is correct!" << std::endl; 
                               ;
    break;}
case 9:
#line 72 "limbaj.y"
{
                                   if (!current->existsId(yyvsp[0].string)) {
                                       current->addVar(yyvsp[-1].string, yyvsp[0].string);
                                   } else {
                                       errorCount++; 
                                       yyerror("Variable already defined");
                                   }
                               ;
    break;}
case 10:
#line 80 "limbaj.y"
{
                                   if (!current->existsId(yyvsp[-3].string)) {
                                       current->addVar(yyvsp[-4].string, yyvsp[-3].string);
                                   } else {
                                       errorCount++; 
                                       yyerror("Variable already defined");
                                   }
                               ;
    break;}
case 21:
#line 117 "limbaj.y"
{ 
                                   /* create function symtable, update current */ 
                               ;
    break;}
case 22:
#line 119 "limbaj.y"
{
                                   /* update current pointer to match the new scope */
                                   /* if ID does not exist in current scope, add function info to the current symtable */
                               ;
    break;}
case 27:
#line 136 "limbaj.y"
{
                                   /* create function symtable, update current */ 
                               ;
    break;}
case 28:
#line 138 "limbaj.y"
{
                                   /* update current pointer to match the new scope */
                                   /* if ID does not exist in current scope, add function info to the current symtable */
                               ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 256 "limbaj.y"

void yyerror(const char * s){
     cout << "error:" << s << " at line: " << yylineno << endl;
}

int main(int argc, char** argv){
     yyin=fopen(argv[1],"r");
     current = new SymTable("global");
     yyparse();
     cout << "Variables:" <<endl;
     current->printVars();
     delete current;
}