#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from limbaj.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "limbaj.y"

#include <iostream>
#include <vector>
#include "utils.h"
extern FILE* yyin;
extern char* yytext;
extern int yylineno;
extern int yylex();





int errorCount = 0;

#line 16 "limbaj.y"
typedef union 
{
     int number;
     float real_number;
     bool true_or_false;
     char caracter;
     char* string;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	BGIN	258
#define	END	259
#define	ASSIGN	260
#define	NR	261
#define	BGINGLOBAL	262
#define	ENDGLOBAL	263
#define	BGINVARS	264
#define	ENDVARS	265
#define	BGINCLASS	266
#define	ENDCLASS	267
#define	BGINFUNC	268
#define	ENDFUNC	269
#define	CLASS	270
#define	EQ	271
#define	NEQ	272
#define	GT	273
#define	LT	274
#define	GTE	275
#define	LTE	276
#define	AND	277
#define	OR	278
#define	NOT	279
#define	PRINT	280
#define	TYPEOF	281
#define	EVAL	282
#define	IF	283
#define	ELSE	284
#define	WHILE	285
#define	FOR	286
#define	DO	287
#define	LOOP	288
#define	BREAK	289
#define	CONTINUE	290
#define	RETURN	291
#define	ID	292
#define	SVAL	293
#define	CHAR	294
#define	STRING	295
#define	FLOAT	296
#define	INT	297
#define	BOOL	298
#define	FVAL	299
#define	IVAL	300
#define	BVAL	301
#define	CVAL	302


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int BGIN;
static const int END;
static const int ASSIGN;
static const int NR;
static const int BGINGLOBAL;
static const int ENDGLOBAL;
static const int BGINVARS;
static const int ENDVARS;
static const int BGINCLASS;
static const int ENDCLASS;
static const int BGINFUNC;
static const int ENDFUNC;
static const int CLASS;
static const int EQ;
static const int NEQ;
static const int GT;
static const int LT;
static const int GTE;
static const int LTE;
static const int AND;
static const int OR;
static const int NOT;
static const int PRINT;
static const int TYPEOF;
static const int EVAL;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int DO;
static const int LOOP;
static const int BREAK;
static const int CONTINUE;
static const int RETURN;
static const int ID;
static const int SVAL;
static const int CHAR;
static const int STRING;
static const int FLOAT;
static const int INT;
static const int BOOL;
static const int FVAL;
static const int IVAL;
static const int BVAL;
static const int CVAL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,BGIN=258
	,END=259
	,ASSIGN=260
	,NR=261
	,BGINGLOBAL=262
	,ENDGLOBAL=263
	,BGINVARS=264
	,ENDVARS=265
	,BGINCLASS=266
	,ENDCLASS=267
	,BGINFUNC=268
	,ENDFUNC=269
	,CLASS=270
	,EQ=271
	,NEQ=272
	,GT=273
	,LT=274
	,GTE=275
	,LTE=276
	,AND=277
	,OR=278
	,NOT=279
	,PRINT=280
	,TYPEOF=281
	,EVAL=282
	,IF=283
	,ELSE=284
	,WHILE=285
	,FOR=286
	,DO=287
	,LOOP=288
	,BREAK=289
	,CONTINUE=290
	,RETURN=291
	,ID=292
	,SVAL=293
	,CHAR=294
	,STRING=295
	,FLOAT=296
	,INT=297
	,BOOL=298
	,FVAL=299
	,IVAL=300
	,BVAL=301
	,CVAL=302


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::BGIN=258;
const int YY_parse_CLASS::END=259;
const int YY_parse_CLASS::ASSIGN=260;
const int YY_parse_CLASS::NR=261;
const int YY_parse_CLASS::BGINGLOBAL=262;
const int YY_parse_CLASS::ENDGLOBAL=263;
const int YY_parse_CLASS::BGINVARS=264;
const int YY_parse_CLASS::ENDVARS=265;
const int YY_parse_CLASS::BGINCLASS=266;
const int YY_parse_CLASS::ENDCLASS=267;
const int YY_parse_CLASS::BGINFUNC=268;
const int YY_parse_CLASS::ENDFUNC=269;
const int YY_parse_CLASS::CLASS=270;
const int YY_parse_CLASS::EQ=271;
const int YY_parse_CLASS::NEQ=272;
const int YY_parse_CLASS::GT=273;
const int YY_parse_CLASS::LT=274;
const int YY_parse_CLASS::GTE=275;
const int YY_parse_CLASS::LTE=276;
const int YY_parse_CLASS::AND=277;
const int YY_parse_CLASS::OR=278;
const int YY_parse_CLASS::NOT=279;
const int YY_parse_CLASS::PRINT=280;
const int YY_parse_CLASS::TYPEOF=281;
const int YY_parse_CLASS::EVAL=282;
const int YY_parse_CLASS::IF=283;
const int YY_parse_CLASS::ELSE=284;
const int YY_parse_CLASS::WHILE=285;
const int YY_parse_CLASS::FOR=286;
const int YY_parse_CLASS::DO=287;
const int YY_parse_CLASS::LOOP=288;
const int YY_parse_CLASS::BREAK=289;
const int YY_parse_CLASS::CONTINUE=290;
const int YY_parse_CLASS::RETURN=291;
const int YY_parse_CLASS::ID=292;
const int YY_parse_CLASS::SVAL=293;
const int YY_parse_CLASS::CHAR=294;
const int YY_parse_CLASS::STRING=295;
const int YY_parse_CLASS::FLOAT=296;
const int YY_parse_CLASS::INT=297;
const int YY_parse_CLASS::BOOL=298;
const int YY_parse_CLASS::FVAL=299;
const int YY_parse_CLASS::IVAL=300;
const int YY_parse_CLASS::BVAL=301;
const int YY_parse_CLASS::CVAL=302;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		283
#define	YYFLAG		-32768
#define	YYNTBASE	64

#define YYTRANSLATE(x) ((unsigned)(x) <= 302 ? yytranslate[x] : 112)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    52,     2,     2,    56,
    57,    50,    48,    59,    49,    63,    51,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    62,    58,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    54,     2,    55,    53,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    60,     2,    61,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,     9,    10,    14,    18,    19,    22,    26,
    28,    30,    32,    34,    36,    39,    45,    47,    51,    53,
    57,    58,    60,    63,    64,    73,    75,    78,    83,    86,
    87,    88,    98,   102,   103,   105,   108,   109,   117,   118,
   126,   130,   132,   136,   137,   140,   146,   150,   152,   155,
   156,   157,   162,   164,   167,   170,   173,   177,   184,   185,
   186,   197,   198,   207,   208,   218,   219,   225,   226,   239,
   242,   245,   249,   250,   255,   260,   266,   270,   280,   284,
   286,   289,   294,   299,   303,   308,   313,   317,   319,   325,
   329,   335,   339,   344,   346,   349,   351,   355,   361,   365,
   371,   375,   381,   385,   391,   395,   401,   405,   411,   413,
   415,   419,   422,   424,   426,   428,   430,   432,   437,   441,
   445,   447,   451,   455,   459,   463
};

static const short yyrhs[] = {    65,
    92,     0,     0,     7,    66,    67,     8,     0,     0,    68,
    73,    82,     0,     9,    69,    10,     0,     0,    71,    58,
     0,    69,    71,    58,     0,    42,     0,    41,     0,    40,
     0,    43,     0,    39,     0,    70,    37,     0,    70,    37,
    54,    90,    55,     0,   104,     0,    72,    59,   110,     0,
   110,     0,    11,    74,    12,     0,     0,    75,     0,    74,
    75,     0,     0,    15,    37,    60,    76,    77,    79,    61,
    58,     0,    78,     0,    77,    78,     0,    37,    62,    70,
    58,     0,    79,    80,     0,     0,     0,    70,    37,    56,
    88,    57,    60,    81,    91,    61,     0,    13,    83,    14,
     0,     0,    84,     0,    83,    84,     0,     0,    70,    37,
    56,    88,    57,    85,    87,     0,     0,    70,    37,    56,
    88,    57,    58,    86,     0,    60,    91,    61,     0,    89,
     0,    88,    59,    89,     0,     0,    70,    37,     0,    70,
    37,    54,    90,    55,     0,    90,    59,    45,     0,    45,
     0,    91,    95,     0,     0,     0,     3,    93,    94,     4,
     0,    95,     0,    94,    95,     0,   106,    58,     0,    71,
    58,     0,    37,    37,    58,     0,    37,    37,    60,   103,
    61,    58,     0,     0,     0,    28,    96,    56,   108,    57,
    60,    94,    61,    97,   102,     0,     0,    30,    98,    56,
   108,    57,    60,    94,    61,     0,     0,    32,    99,    60,
    94,    61,    30,    56,   108,    57,     0,     0,    33,   100,
    60,    94,    61,     0,     0,    31,   101,    56,   104,    58,
   108,    58,   104,    57,    60,    94,    61,     0,    35,    58,
     0,    34,    58,     0,    36,   108,    58,     0,     0,    29,
    60,    94,    61,     0,    37,     5,   110,    58,     0,   103,
    37,     5,   110,    58,     0,   105,     5,   110,     0,    70,
    37,    54,    90,    55,     5,    60,    72,    61,     0,    37,
    63,    37,     0,    37,     0,    70,    37,     0,    37,    54,
    90,    55,     0,    37,    56,   107,    57,     0,    37,    56,
    57,     0,    25,    56,   110,    57,     0,    26,    56,   110,
    57,     0,   107,    59,   110,     0,   110,     0,    56,   108,
    22,   108,    57,     0,   108,    22,   108,     0,    56,   108,
    23,   108,    57,     0,   108,    23,   108,     0,    56,    24,
   108,    57,     0,    46,     0,    24,   108,     0,   110,     0,
   110,    16,   110,     0,    56,   110,    16,   110,    57,     0,
   110,    17,   110,     0,    56,   110,    17,   110,    57,     0,
   110,    18,   110,     0,    56,   110,    18,   110,    57,     0,
   110,    20,   110,     0,    56,   110,    20,   110,    57,     0,
   110,    19,   110,     0,    56,   110,    19,   110,    57,     0,
   110,    21,   110,     0,    56,   110,    21,   110,    57,     0,
   111,     0,   109,     0,    56,   110,    57,     0,    49,   110,
     0,    37,     0,    45,     0,    44,     0,    47,     0,    38,
     0,    37,    54,    90,    55,     0,    37,    63,    37,     0,
    37,    63,   106,     0,   106,     0,   110,    48,   110,     0,
   110,    50,   110,     0,   110,    51,   110,     0,   110,    49,
   110,     0,   110,    52,   110,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    48,    55,    59,    60,    64,    68,    69,    73,    74,    77,
    82,    87,    92,    97,   105,   111,   117,   120,   121,   125,
   126,   129,   130,   135,   146,   153,   154,   158,   169,   170,
   175,   188,   199,   200,   204,   205,   209,   219,   223,   231,
   237,   242,   243,   244,   249,   257,   268,   269,   274,   275,
   280,   284,   291,   292,   297,   298,   299,   300,   301,   306,
   312,   316,   322,   327,   333,   338,   344,   349,   355,   360,
   361,   362,   365,   366,   371,   372,   375,   376,   379,   380,
   396,   397,   401,   407,   408,   409,   414,   415,   419,   420,
   421,   422,   423,   424,   425,   426,   429,   430,   431,   432,
   433,   434,   435,   436,   437,   438,   439,   440,   443,   444,
   445,   446,   447,   448,   449,   450,   451,   452,   453,   454,
   455,   459,   460,   461,   462,   463
};

static const char * const yytname[] = {   "$","error","$illegal.","BGIN","END",
"ASSIGN","NR","BGINGLOBAL","ENDGLOBAL","BGINVARS","ENDVARS","BGINCLASS","ENDCLASS",
"BGINFUNC","ENDFUNC","CLASS","EQ","NEQ","GT","LT","GTE","LTE","AND","OR","NOT",
"PRINT","TYPEOF","EVAL","IF","ELSE","WHILE","FOR","DO","LOOP","BREAK","CONTINUE",
"RETURN","ID","SVAL","CHAR","STRING","FLOAT","INT","BOOL","FVAL","IVAL","BVAL",
"CVAL","'+'","'-'","'*'","'/'","'%'","'^'","'['","']'","'('","')'","';'","','",
"'{'","'}'","':'","'.'","progr","global_declarations","@1","declarations","vars_declarations",
"decl_vars","TYPE","decl_var","init_list","class_declarations","decl_classes",
"decl_class","@2","membs_list","class_memb","methods_list","method","@3","func_declarations",
"decl_funcs","def_func","@4","@5","function_definition","list_param","param",
"list_array","fblock","main","@6","list","statement","@7","@8","@9","@10","@11",
"@12","else_statement","init_instante","assignment_stmt","left_hand_side","call_func",
"call_list","bool_expr","logical_expr","expr","arithm_expr",""
};
#endif

static const short yyr1[] = {     0,
    64,    66,    65,    65,    67,    68,    68,    69,    69,    70,
    70,    70,    70,    70,    71,    71,    71,    72,    72,    73,
    73,    74,    74,    76,    75,    77,    77,    78,    79,    79,
    81,    80,    82,    82,    83,    83,    85,    84,    86,    84,
    87,    88,    88,    88,    89,    89,    90,    90,    91,    91,
    93,    92,    94,    94,    95,    95,    95,    95,    96,    97,
    95,    98,    95,    99,    95,   100,    95,   101,    95,    95,
    95,    95,   102,   102,   103,   103,   104,   104,   105,   105,
   105,   105,   106,   106,   106,   106,   107,   107,   108,   108,
   108,   108,   108,   108,   108,   108,   109,   109,   109,   109,
   109,   109,   109,   109,   109,   109,   109,   109,   110,   110,
   110,   110,   110,   110,   110,   110,   110,   110,   110,   110,
   110,   111,   111,   111,   111,   111
};

static const short yyr2[] = {     0,
     2,     0,     4,     0,     3,     3,     0,     2,     3,     1,
     1,     1,     1,     1,     2,     5,     1,     3,     1,     3,
     0,     1,     2,     0,     8,     1,     2,     4,     2,     0,
     0,     9,     3,     0,     1,     2,     0,     7,     0,     7,
     3,     1,     3,     0,     2,     5,     3,     1,     2,     0,
     0,     4,     1,     2,     2,     2,     3,     6,     0,     0,
    10,     0,     8,     0,     9,     0,     5,     0,    12,     2,
     2,     3,     0,     4,     4,     5,     3,     9,     3,     1,
     2,     4,     4,     3,     4,     4,     3,     1,     5,     3,
     5,     3,     4,     1,     2,     1,     3,     5,     3,     5,
     3,     5,     3,     5,     3,     5,     3,     5,     1,     1,
     3,     2,     1,     1,     1,     1,     1,     4,     3,     3,
     1,     3,     3,     3,     3,     3
};

static const short yydefact[] = {     4,
     2,     0,     7,    51,     1,     0,     0,    21,     0,    80,
    14,    12,    11,    10,    13,     0,     0,     0,    17,     0,
     3,     0,    34,     0,     0,    59,    62,    68,    64,    66,
     0,     0,     0,    80,     0,     0,    53,     0,     0,     0,
     6,     0,    15,     8,     0,     0,     0,    22,     0,     5,
     0,     0,     0,     0,     0,     0,     0,    71,    70,     0,
   113,   117,   115,   114,    94,   116,     0,     0,   121,     0,
   110,    96,   109,     0,     0,    56,    52,    54,    55,    48,
     0,    79,     9,     0,     0,    77,     0,    20,    23,     0,
     0,    35,     0,     0,     0,     0,     0,     0,     0,    95,
     0,     0,   112,     0,     0,    96,     0,     0,    72,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    57,     0,    84,     0,    88,    82,     0,     0,     0,    24,
     0,    33,    36,    85,    86,     0,     0,     0,     0,     0,
     0,     0,   119,   120,    95,     0,     0,     0,     0,     0,
     0,     0,     0,   111,    90,    92,    97,    99,   101,   105,
   103,   107,   122,   125,   123,   124,   126,     0,     0,    83,
     0,    47,    16,     0,    44,     0,     0,    81,     0,     0,
    67,   118,    93,    90,    92,    97,    99,   101,   105,   103,
   107,     0,     0,     0,    87,     0,     0,    30,    26,     0,
     0,    42,     0,     0,     0,     0,     0,    89,    91,    98,
   100,   102,   106,   104,   108,     0,     0,    58,     0,     0,
    27,     0,    45,    37,     0,     0,     0,     0,     0,     0,
    75,     0,     0,    19,     0,     0,     0,    29,     0,    39,
     0,    43,    60,    63,     0,     0,     0,    76,     0,    78,
    28,    25,     0,     0,    40,    50,    38,    73,     0,    65,
    18,    44,    46,     0,     0,    61,     0,     0,    41,    49,
     0,     0,     0,     0,    69,    31,    74,    50,     0,    32,
     0,     0,     0
};

static const short yydefgoto[] = {   281,
     2,     3,     7,     8,    16,    17,    35,   233,    23,    47,
    48,   174,   198,   199,   222,   238,   278,    50,    91,    92,
   241,   255,   257,   201,   202,    81,   264,     5,     9,    36,
    37,    53,   258,    54,    56,    57,    55,   266,   169,    19,
    20,    69,   124,    70,    71,    72,    73
};

static const short yypact[] = {    49,
-32768,    83,    94,-32768,-32768,   579,    96,   114,   564,   -28,
-32768,-32768,-32768,-32768,-32768,   146,    55,    72,-32768,   132,
-32768,   140,   149,   103,   107,-32768,-32768,-32768,-32768,-32768,
   113,   116,   484,   153,   119,   257,-32768,   126,   125,   156,
-32768,   147,     6,-32768,    97,   193,   112,-32768,   185,-32768,
    97,    97,   186,   187,   196,   197,   199,-32768,-32768,   484,
    31,-32768,-32768,-32768,-32768,-32768,    97,   517,-32768,    -7,
-32768,   486,-32768,   -37,   531,-32768,-32768,-32768,-32768,-32768,
    29,-32768,-32768,   125,    97,   486,   200,-32768,-32768,   217,
   473,-32768,    50,   229,   484,   484,   579,   564,   564,-32768,
   125,    16,   162,   484,    17,   255,   484,   484,-32768,    97,
    97,    97,    97,    97,    97,    97,    97,    97,    97,    97,
-32768,   219,-32768,    88,   486,-32768,   221,    36,   255,-32768,
   208,-32768,-32768,-32768,-32768,   -14,     2,   230,   210,   288,
   320,    81,   213,-32768,   227,   484,   484,    97,    97,    97,
    97,    97,    97,-32768,-32768,   273,    13,    13,   284,   284,
   284,   284,   162,   162,-32768,-32768,-32768,   296,   -25,-32768,
    97,-32768,   297,   278,   185,   266,   277,   263,   484,   313,
-32768,-32768,-32768,   287,    -5,   183,   290,   475,   496,   534,
   560,    97,   353,   306,   486,   305,   304,   278,-32768,   330,
   151,-32768,   564,   564,   125,    -3,   314,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,   100,    97,-32768,    97,   185,
-32768,   180,   318,   329,   185,   343,   366,    84,   579,   484,
-32768,   148,   177,   486,   331,   332,   351,-32768,   125,-32768,
   333,-32768,-32768,-32768,   297,   338,    26,-32768,    97,-32768,
-32768,-32768,   354,   102,-32768,-32768,-32768,   382,   352,-32768,
   486,   185,-32768,   389,   356,-32768,   564,   194,-32768,-32768,
   564,   412,   358,   435,-32768,-32768,-32768,-32768,   458,-32768,
   413,   433,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,-32768,-32768,   -47,    22,-32768,-32768,-32768,
   387,-32768,-32768,   237,-32768,-32768,-32768,-32768,-32768,   345,
-32768,-32768,-32768,   179,   214,   -79,   178,-32768,-32768,   -95,
   -35,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   -91,
-32768,    -9,-32768,   -50,-32768,   -38,-32768
};


#define	YYLAST		622


static const short yytable[] = {    38,
    78,    90,   140,   141,   128,   139,    86,   107,   108,   100,
   -81,   193,    93,    94,   107,   108,   107,   105,   107,   108,
   121,   142,   122,   107,   108,    39,    38,    18,   103,   106,
   112,   113,   114,   115,    40,   194,   125,    42,   146,   147,
    24,    25,   176,    90,   136,   137,   129,   107,   108,   138,
   109,   209,   143,   145,   229,     1,   155,   156,   177,    84,
   116,   117,   118,   119,   120,   110,   111,   112,   113,   114,
   115,   157,   158,   159,   160,   161,   162,   163,   164,   165,
   166,   167,   260,   126,   101,     4,    75,   127,    38,    38,
   173,    43,   144,   102,   127,   184,   185,   116,   117,   118,
   119,   120,     6,    21,    78,    78,   134,   226,   227,   186,
   187,   188,   189,   190,   191,   110,   111,   112,   113,   114,
   115,    24,    25,    88,    22,   228,    46,   200,   206,    44,
    38,    38,   195,    61,    62,   182,    45,   246,   245,   127,
    63,    64,   127,    66,   170,    67,   171,   116,   117,   118,
   119,   120,    85,   216,    46,    41,   263,   231,    51,   254,
   127,    49,    52,   110,   111,   112,   113,   114,   115,    80,
    58,   272,   235,    59,   237,   274,    76,   200,   232,   247,
   234,   138,    10,    79,    11,    12,    13,    14,    15,    74,
    78,    78,    82,    38,    38,   116,   117,   118,   119,   120,
   112,   113,   114,   115,    83,   248,    39,   224,    75,   225,
   261,   118,   119,   120,   200,    40,    38,    38,    11,    12,
    13,    14,    15,    11,    12,    13,    14,    15,   270,    87,
   116,   117,   118,   119,   120,   249,    78,   250,    78,   210,
   236,    95,    96,   270,   110,   111,   112,   113,   114,   115,
   273,    97,   225,   131,    38,   168,    98,    38,    99,   130,
    77,    38,    38,   175,    38,   172,   178,   179,    75,    38,
   148,   149,   150,   151,   152,   153,   116,   117,   118,   119,
   120,    24,    25,   183,    26,   135,    27,    28,    29,    30,
    31,    32,    33,    34,   107,    11,    12,    13,    14,    15,
   192,   196,   116,   117,   118,   119,   120,   112,   113,   114,
   115,   154,    24,    25,   197,    26,   205,    27,    28,    29,
    30,    31,    32,    33,    34,   203,    11,    12,    13,    14,
    15,   116,   117,   118,   119,   120,   204,   116,   117,   118,
   119,   120,   207,   208,    24,    25,   211,    26,   180,    27,
    28,    29,    30,    31,    32,    33,    34,   217,    11,    12,
    13,    14,    15,   218,   219,   220,   223,    24,    25,   230,
    26,   239,    27,    28,    29,    30,    31,    32,    33,    34,
   181,    11,    12,    13,    14,    15,   240,   253,   251,   252,
    24,    25,   256,    26,   259,    27,    28,    29,    30,    31,
    32,    33,    34,   243,    11,    12,    13,    14,    15,   262,
   265,   267,   282,    24,    25,   271,    26,   276,    27,    28,
    29,    30,    31,    32,    33,    34,   244,    11,    12,    13,
    14,    15,   283,    89,   221,   133,    24,    25,   242,    26,
   268,    27,    28,    29,    30,    31,    32,    33,    34,   269,
    11,    12,    13,    14,    15,   279,     0,     0,     0,    24,
    25,     0,    26,     0,    27,    28,    29,    30,    31,    32,
    33,    34,   275,    11,    12,    13,    14,    15,     0,     0,
     0,     0,    24,    25,     0,    26,   132,    27,    28,    29,
    30,    31,    32,    33,    34,   277,    11,    12,    13,    14,
    15,   110,   111,   112,   113,   114,   115,    60,    24,    25,
     0,    11,    12,    13,    14,    15,     0,     0,   280,     0,
    61,    62,   116,   117,   118,   119,   120,    63,    64,    65,
    66,   212,    67,   116,   117,   118,   119,   120,     0,    68,
   104,    24,    25,   116,   117,   118,   119,   120,     0,     0,
     0,     0,   213,    61,    62,    24,    25,     0,     0,     0,
    63,    64,    65,    66,     0,    67,     0,    61,    62,     0,
     0,     0,    68,     0,    63,    64,     0,    66,     0,    67,
     0,   116,   117,   118,   119,   120,    85,   123,    24,    25,
   214,    26,     0,    27,    28,    29,    30,    31,    32,    33,
    34,     0,    11,    12,    13,    14,    15,   116,   117,   118,
   119,   120,     0,     0,     0,    10,   215,    11,    12,    13,
    14,    15
};

static const short yycheck[] = {     9,
    36,    49,    98,    99,    84,    97,    45,    22,    23,    60,
     5,    37,    51,    52,    22,    23,    22,    68,    22,    23,
    58,   101,    60,    22,    23,    54,    36,     6,    67,    68,
    18,    19,    20,    21,    63,    61,    75,    16,    22,    23,
    25,    26,    57,    91,    95,    96,    85,    22,    23,    97,
    58,    57,    37,   104,    58,     7,   107,   108,    57,    54,
    48,    49,    50,    51,    52,    16,    17,    18,    19,    20,
    21,   110,   111,   112,   113,   114,   115,   116,   117,   118,
   119,   120,    57,    55,    54,     3,    56,    59,    98,    99,
    55,    37,   102,    63,    59,   146,   147,    48,    49,    50,
    51,    52,     9,     8,   140,   141,    57,   203,   204,   148,
   149,   150,   151,   152,   153,    16,    17,    18,    19,    20,
    21,    25,    26,    12,    11,   205,    15,   175,   179,    58,
   140,   141,   171,    37,    38,    55,     5,   229,    55,    59,
    44,    45,    59,    47,    57,    49,    59,    48,    49,    50,
    51,    52,    56,   192,    15,    10,    55,    58,    56,   239,
    59,    13,    56,    16,    17,    18,    19,    20,    21,    45,
    58,   267,   220,    58,   222,   271,    58,   225,   217,   230,
   219,   229,    37,    58,    39,    40,    41,    42,    43,    37,
   226,   227,    37,   203,   204,    48,    49,    50,    51,    52,
    18,    19,    20,    21,    58,    58,    54,    57,    56,    59,
   249,    50,    51,    52,   262,    63,   226,   227,    39,    40,
    41,    42,    43,    39,    40,    41,    42,    43,   264,    37,
    48,    49,    50,    51,    52,    59,   272,    61,   274,    57,
    61,    56,    56,   279,    16,    17,    18,    19,    20,    21,
    57,    56,    59,    37,   264,    37,    60,   267,    60,    60,
     4,   271,   272,    56,   274,    45,    37,    58,    56,   279,
    16,    17,    18,    19,    20,    21,    48,    49,    50,    51,
    52,    25,    26,    57,    28,    57,    30,    31,    32,    33,
    34,    35,    36,    37,    22,    39,    40,    41,    42,    43,
     5,     5,    48,    49,    50,    51,    52,    18,    19,    20,
    21,    57,    25,    26,    37,    28,    54,    30,    31,    32,
    33,    34,    35,    36,    37,    60,    39,    40,    41,    42,
    43,    48,    49,    50,    51,    52,    60,    48,    49,    50,
    51,    52,    30,    57,    25,    26,    57,    28,    61,    30,
    31,    32,    33,    34,    35,    36,    37,     5,    39,    40,
    41,    42,    43,    58,    60,    62,    37,    25,    26,    56,
    28,    54,    30,    31,    32,    33,    34,    35,    36,    37,
    61,    39,    40,    41,    42,    43,    58,    37,    58,    58,
    25,    26,    60,    28,    57,    30,    31,    32,    33,    34,
    35,    36,    37,    61,    39,    40,    41,    42,    43,    56,
    29,    60,     0,    25,    26,    60,    28,    60,    30,    31,
    32,    33,    34,    35,    36,    37,    61,    39,    40,    41,
    42,    43,     0,    47,   198,    91,    25,    26,   225,    28,
   262,    30,    31,    32,    33,    34,    35,    36,    37,    61,
    39,    40,    41,    42,    43,   278,    -1,    -1,    -1,    25,
    26,    -1,    28,    -1,    30,    31,    32,    33,    34,    35,
    36,    37,    61,    39,    40,    41,    42,    43,    -1,    -1,
    -1,    -1,    25,    26,    -1,    28,    14,    30,    31,    32,
    33,    34,    35,    36,    37,    61,    39,    40,    41,    42,
    43,    16,    17,    18,    19,    20,    21,    24,    25,    26,
    -1,    39,    40,    41,    42,    43,    -1,    -1,    61,    -1,
    37,    38,    48,    49,    50,    51,    52,    44,    45,    46,
    47,    57,    49,    48,    49,    50,    51,    52,    -1,    56,
    24,    25,    26,    48,    49,    50,    51,    52,    -1,    -1,
    -1,    -1,    57,    37,    38,    25,    26,    -1,    -1,    -1,
    44,    45,    46,    47,    -1,    49,    -1,    37,    38,    -1,
    -1,    -1,    56,    -1,    44,    45,    -1,    47,    -1,    49,
    -1,    48,    49,    50,    51,    52,    56,    57,    25,    26,
    57,    28,    -1,    30,    31,    32,    33,    34,    35,    36,
    37,    -1,    39,    40,    41,    42,    43,    48,    49,    50,
    51,    52,    -1,    -1,    -1,    37,    57,    39,    40,    41,
    42,    43
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 48 "limbaj.y"
{ 
                                   if (errorCount == 0) 
                                       std::cout << "The program is correct!" << std::endl; 
                               ;
    break;}
case 2:
#line 55 "limbaj.y"
{
                                    currentTable = globalTable;
                                    tables.push_back(globalTable);
                                ;
    break;}
case 10:
#line 78 "limbaj.y"
{
          currentVariable.type.typeName = TYPE_INT;
          currentFunction.returnType = TYPE_INT;
     ;
    break;}
case 11:
#line 83 "limbaj.y"
{
          currentVariable.type.typeName = TYPE_FLOAT;
          currentFunction.returnType = TYPE_FLOAT;
     ;
    break;}
case 12:
#line 88 "limbaj.y"
{
          currentVariable.type.typeName = TYPE_STRING;
          currentFunction.returnType = TYPE_STRING;
     ;
    break;}
case 13:
#line 93 "limbaj.y"
{
          currentVariable.type.typeName = TYPE_BOOL;
          currentFunction.returnType = TYPE_BOOL;
     ;
    break;}
case 14:
#line 98 "limbaj.y"
{
          currentVariable.type.typeName = TYPE_CHAR;
          currentFunction.returnType = TYPE_CHAR;
     ;
    break;}
case 15:
#line 106 "limbaj.y"
{
                                    if(!exists_or_add(yyvsp[0].string, false)) {

                                    }
                                ;
    break;}
case 16:
#line 112 "limbaj.y"
{
                                   if(!exists_or_add(yyvsp[-3].string, true)) {

                                   }
                                ;
    break;}
case 24:
#line 135 "limbaj.y"
{
        // Creează tabelă pentru clasa curentă
        if (currentTable->existsId(yyvsp[-1].string)) { // Verifică dacă clasa există deja
            errorCount++;
            yyerror(("Class already defined at line: " + std::to_string(yylineno)).c_str());
        } else {
            currentClass.name = yyvsp[-1].string;
            currentTable->addClass(yyvsp[-1].string);
            currentTable = new SymTable(yyvsp[-1].string, currentTable);  // Creează un nou tabel de simboluri pentru clasă
            tables.push_back(currentTable); // Adaugă în lista globală de tabele
        }
    ;
    break;}
case 25:
#line 146 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 28:
#line 159 "limbaj.y"
{
                                   if (!currentTable->existsId(yyvsp[-3].string)) {
                                       currentTable->addVar(currentVariable.type.typeName, yyvsp[-3].string);
                                   } else {
                                       errorCount++; 
                                       yyerror(("Variable already defined at line: " + std::to_string(yylineno)).c_str());
                                   }
                               ;
    break;}
case 31:
#line 175 "limbaj.y"
{
        // Verifică dacă funcția este deja definită
        if (currentTable->existsFunc(yyvsp[-4].string)) 
        { 
            errorCount++;
            yyerror(("Function " + std::string(yyvsp[-4].string) + " already defined at line: " + std::to_string(yylineno)).c_str());
        } else {
            // Adaugă funcția în tabela simbolurilor a clasei
            currentTable->addFunc(currentFunction.returnType, yyvsp[-4].string, currentParams, currentClass.name);
            currentTable = new SymTable(yyvsp[-4].string, currentTable);  // Creează un nou tabel de simboluri pentru clasă
            tables.push_back(currentTable);
        }
    ;
    break;}
case 32:
#line 189 "limbaj.y"
{
        // Revenire la tabelul simbolurilor al clasei
        currentTable = currentTable->prev;
        //current = current->prev;
        //stergerea parametrilor
        currentParams.clear();
    ;
    break;}
case 37:
#line 210 "limbaj.y"
{   
                        if(!currentTable->existsFunc(yyvsp[-3].string)) {
                            currentTable->addFunc(currentFunction.returnType, yyvsp[-3].string, currentParams);
                        }
                        currentTable = new SymTable(yyvsp[-3].string, currentTable); // Crează un tabel de simboluri pentru funcția curentă
                        tables.push_back(currentTable);  // Adaugă tabelul global
                        currentFunction.name = yyvsp[-3].string; 
                    ;
    break;}
case 38:
#line 219 "limbaj.y"
{
                        currentParams.clear();
                        currentTable = currentTable->prev; // Revenire la scopul părinte
                    ;
    break;}
case 39:
#line 223 "limbaj.y"
{
                        if(!currentTable->existsFunc(yyvsp[-4].string)) {
                            currentTable->addFunc(currentFunction.returnType, yyvsp[-4].string, currentParams);
                        }
                        currentTable = new SymTable(yyvsp[-4].string, currentTable); // Crează un tabel de simboluri pentru funcția curentă
                        tables.push_back(currentTable);  // Adaugă tabelul global

                    ;
    break;}
case 40:
#line 231 "limbaj.y"
{
                        currentParams.clear();
                        currentTable = currentTable->prev; // Revenire la scopul părinte
                    ;
    break;}
case 45:
#line 250 "limbaj.y"
{
                                    currentVariable.name = yyvsp[0].string;
                                    currentVariable.type.isArray = false;

                                    currentParams.push_back(currentVariable);
                                    
                                ;
    break;}
case 46:
#line 258 "limbaj.y"
{
                                    currentVariable.name = yyvsp[-3].string;
                                    currentVariable.type.isArray = true;

                                    currentParams.push_back(currentVariable);
                                ;
    break;}
case 47:
#line 268 "limbaj.y"
{currentArraySizes.push_back(yyvsp[0].number);
    break;}
case 48:
#line 269 "limbaj.y"
{ currentArraySizes.push_back(yyvsp[0].number);
    break;}
case 51:
#line 280 "limbaj.y"
{ 
        // Creare tabelă pentru scopul main
        currentTable = new SymTable("main", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 52:
#line 284 "limbaj.y"
{
        // Revenire la scopul global
        currentTable = currentTable->prev;
    ;
    break;}
case 59:
#line 302 "limbaj.y"
{
        currentTable = new SymTable("if", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 60:
#line 307 "limbaj.y"
{
        currentTable = new SymTable("else", currentTable->prev);
        tables.push_back(currentTable);
    ;
    break;}
case 61:
#line 312 "limbaj.y"
{  
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 62:
#line 317 "limbaj.y"
{
        // Creează o tabelă pentru scopul WHILE
        currentTable = new SymTable("while", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 63:
#line 323 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 64:
#line 328 "limbaj.y"
{
        // Creează o tabelă pentru scopul WHILE
        currentTable = new SymTable("do-while", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 65:
#line 334 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 66:
#line 339 "limbaj.y"
{
        // Creează o tabelă pentru scopul LOOP
        currentTable = new SymTable("loop", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 67:
#line 345 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 68:
#line 350 "limbaj.y"
{
        // Creează o tabelă pentru scopul FOR
        currentTable = new SymTable("for", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 69:
#line 356 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 80:
#line 381 "limbaj.y"
{
                                currentVariable.name = yyvsp[0].string;
                                currentVariable.type.isArray = 0;
                                
                                p = currentTable;

                                while(p->prev!=nullptr)
                                {
                                    if(p->existsId(yyvsp[0].string))
                                    {
                                        break;
                                    }
                                    p = p->prev;
                                }
                          ;
    break;}
case 83:
#line 401 "limbaj.y"
{
                                if (!currentTable->existsId(yyvsp[-3].string)) { // Verifică dacă funcția există
                                    errorCount++;
                                    yyerror(("Function " + std::string(yyvsp[-3].string) + " not declared at line: " + std::to_string(yylineno)).c_str());
                                }
                           ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 468 "limbaj.y"

void yyerror(const char * s){
     cout << "error: " << s << " at line: " << yylineno << endl;
}

int main(int argc, char** argv) {
    #ifdef YYDEBUG
    yydebug = 1;
    #endif
    yyin = fopen(argv[1], "r");
    //current = new SymTable("global");
    //tables.push_back(current);
    yyparse();

    //std::cout << "Variables in global scope:" << std::endl;
    for(auto table : tables) {
        table->printTable("scope.txt");
    }
    
    // Eliberare memorie pentru toate tabelele
    for (SymTable* table : tables) {
        delete table;
    }

    if (errorCount > 0) {
        std::cout << "There were " << errorCount << " errors." << std::endl;
    } else {
        std::cout << "The program is correct!" << std::endl;
    }

    return 0;
}
