#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from limbaj.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "limbaj.y"

#include <iostream>
#include <vector>
#include "SymTable.h"
#include "AST.h"
extern FILE* yyin;
extern char* yytext;
extern int yylineno;
extern int yylex();

void yyerror(const char * s);

class SymTable* current;
vector<SymTable*> tables;
SymTable* globalTable = new SymTable("global");
SymTable* currentTable = globalTable;

int errorCount = 0;

#line 20 "limbaj.y"
typedef union 
{
     int number;
     float real_number;
     bool true_or_false;
     char caracter;
     char* string;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	BGIN	258
#define	END	259
#define	ASSIGN	260
#define	NR	261
#define	BGINGLOBAL	262
#define	ENDGLOBAL	263
#define	BGINVARS	264
#define	ENDVARS	265
#define	BGINCLASS	266
#define	ENDCLASS	267
#define	BGINFUNC	268
#define	ENDFUNC	269
#define	CLASS	270
#define	CONST	271
#define	EQ	272
#define	NEQ	273
#define	GT	274
#define	LT	275
#define	GTE	276
#define	LTE	277
#define	AND	278
#define	OR	279
#define	NOT	280
#define	PRINT	281
#define	TYPEOF	282
#define	EVAL	283
#define	IF	284
#define	ELSE	285
#define	WHILE	286
#define	FOR	287
#define	DO	288
#define	LOOP	289
#define	BREAK	290
#define	CONTINUE	291
#define	RETURN	292
#define	ID	293
#define	TYPE	294
#define	STRING	295
#define	CHAR	296
#define	FLOAT	297
#define	INT	298
#define	BOOL	299


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int BGIN;
static const int END;
static const int ASSIGN;
static const int NR;
static const int BGINGLOBAL;
static const int ENDGLOBAL;
static const int BGINVARS;
static const int ENDVARS;
static const int BGINCLASS;
static const int ENDCLASS;
static const int BGINFUNC;
static const int ENDFUNC;
static const int CLASS;
static const int CONST;
static const int EQ;
static const int NEQ;
static const int GT;
static const int LT;
static const int GTE;
static const int LTE;
static const int AND;
static const int OR;
static const int NOT;
static const int PRINT;
static const int TYPEOF;
static const int EVAL;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int DO;
static const int LOOP;
static const int BREAK;
static const int CONTINUE;
static const int RETURN;
static const int ID;
static const int TYPE;
static const int STRING;
static const int CHAR;
static const int FLOAT;
static const int INT;
static const int BOOL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,BGIN=258
	,END=259
	,ASSIGN=260
	,NR=261
	,BGINGLOBAL=262
	,ENDGLOBAL=263
	,BGINVARS=264
	,ENDVARS=265
	,BGINCLASS=266
	,ENDCLASS=267
	,BGINFUNC=268
	,ENDFUNC=269
	,CLASS=270
	,CONST=271
	,EQ=272
	,NEQ=273
	,GT=274
	,LT=275
	,GTE=276
	,LTE=277
	,AND=278
	,OR=279
	,NOT=280
	,PRINT=281
	,TYPEOF=282
	,EVAL=283
	,IF=284
	,ELSE=285
	,WHILE=286
	,FOR=287
	,DO=288
	,LOOP=289
	,BREAK=290
	,CONTINUE=291
	,RETURN=292
	,ID=293
	,TYPE=294
	,STRING=295
	,CHAR=296
	,FLOAT=297
	,INT=298
	,BOOL=299


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::BGIN=258;
const int YY_parse_CLASS::END=259;
const int YY_parse_CLASS::ASSIGN=260;
const int YY_parse_CLASS::NR=261;
const int YY_parse_CLASS::BGINGLOBAL=262;
const int YY_parse_CLASS::ENDGLOBAL=263;
const int YY_parse_CLASS::BGINVARS=264;
const int YY_parse_CLASS::ENDVARS=265;
const int YY_parse_CLASS::BGINCLASS=266;
const int YY_parse_CLASS::ENDCLASS=267;
const int YY_parse_CLASS::BGINFUNC=268;
const int YY_parse_CLASS::ENDFUNC=269;
const int YY_parse_CLASS::CLASS=270;
const int YY_parse_CLASS::CONST=271;
const int YY_parse_CLASS::EQ=272;
const int YY_parse_CLASS::NEQ=273;
const int YY_parse_CLASS::GT=274;
const int YY_parse_CLASS::LT=275;
const int YY_parse_CLASS::GTE=276;
const int YY_parse_CLASS::LTE=277;
const int YY_parse_CLASS::AND=278;
const int YY_parse_CLASS::OR=279;
const int YY_parse_CLASS::NOT=280;
const int YY_parse_CLASS::PRINT=281;
const int YY_parse_CLASS::TYPEOF=282;
const int YY_parse_CLASS::EVAL=283;
const int YY_parse_CLASS::IF=284;
const int YY_parse_CLASS::ELSE=285;
const int YY_parse_CLASS::WHILE=286;
const int YY_parse_CLASS::FOR=287;
const int YY_parse_CLASS::DO=288;
const int YY_parse_CLASS::LOOP=289;
const int YY_parse_CLASS::BREAK=290;
const int YY_parse_CLASS::CONTINUE=291;
const int YY_parse_CLASS::RETURN=292;
const int YY_parse_CLASS::ID=293;
const int YY_parse_CLASS::TYPE=294;
const int YY_parse_CLASS::STRING=295;
const int YY_parse_CLASS::CHAR=296;
const int YY_parse_CLASS::FLOAT=297;
const int YY_parse_CLASS::INT=298;
const int YY_parse_CLASS::BOOL=299;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		287
#define	YYFLAG		-32768
#define	YYNTBASE	61

#define YYTRANSLATE(x) ((unsigned)(x) <= 299 ? yytranslate[x] : 101)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    49,     2,     2,    53,
    54,    47,    45,    59,    46,    60,    48,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    58,    55,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    51,     2,    52,    50,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    56,     2,    57,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     7,     8,    12,    16,    17,    20,    24,    27,
    33,    37,    38,    40,    43,    44,    53,    55,    58,    63,
    66,    67,    68,    78,    82,    83,    85,    88,    89,    99,
   101,   105,   106,   109,   113,   115,   116,   123,   124,   125,
   130,   133,   137,   139,   141,   144,   150,   151,   160,   161,
   180,   181,   190,   199,   200,   208,   209,   222,   224,   226,
   228,   231,   236,   242,   247,   252,   256,   260,   267,   274,
   281,   287,   293,   298,   302,   307,   312,   316,   323,   325,
   330,   336,   340,   346,   350,   355,   357,   360,   362,   366,
   372,   376,   382,   386,   392,   396,   402,   406,   412,   416,
   422,   424,   428,   432,   436,   440,   444,   448,   451,   453,
   455,   457,   459,   464,   468,   472
};

static const short yyrhs[] = {    62,
    85,     0,     7,    63,     8,     0,     0,    64,    67,    76,
     0,     9,    65,    10,     0,     0,    66,    55,     0,    65,
    66,    55,     0,    39,    38,     0,    39,    38,    51,    82,
    52,     0,    11,    68,    12,     0,     0,    69,     0,    68,
    69,     0,     0,    15,    38,    56,    70,    71,    73,    57,
    55,     0,    72,     0,    71,    72,     0,    38,    58,    39,
    55,     0,    73,    74,     0,     0,     0,    39,    38,    53,
    80,    54,    56,    75,    83,    57,     0,    13,    77,    14,
     0,     0,    78,     0,    77,    78,     0,     0,    39,    38,
    53,    80,    54,    56,    79,    83,    57,     0,    81,     0,
    80,    59,    81,     0,     0,    39,    38,     0,    82,    59,
    43,     0,    43,     0,     0,    56,    84,    83,    88,    55,
    57,     0,     0,     0,     3,    86,    87,     4,     0,    88,
    55,     0,    87,    88,    55,     0,    96,     0,    66,     0,
    38,    38,     0,    38,    38,    56,    94,    57,     0,     0,
    29,    53,    98,    54,    56,    89,    87,    57,     0,     0,
    29,    53,    98,    54,    56,    87,    57,    30,    56,    87,
    57,    90,    87,    57,    30,    56,    87,    57,     0,     0,
    31,    53,    98,    54,    56,    91,    87,    57,     0,    33,
    56,    87,    57,    31,    53,    98,    54,     0,     0,    34,
    56,    87,    57,    92,    87,    57,     0,     0,    32,    53,
    95,    55,    98,    55,    95,    54,    56,    93,    87,    57,
     0,    95,     0,    36,     0,    35,     0,    37,    98,     0,
    38,     5,   100,    55,     0,    94,    38,     5,   100,    55,
     0,    39,    38,     5,   100,     0,    39,    38,     5,    40,
     0,    38,     5,   100,     0,    38,     5,    40,     0,    38,
    51,    82,    52,     5,   100,     0,    38,    51,    82,    52,
     5,    96,     0,    38,    51,    82,    52,     5,    40,     0,
    38,    60,    38,     5,   100,     0,    38,    60,    38,     5,
    40,     0,    38,    53,    97,    54,     0,    38,    53,    54,
     0,    26,    53,    40,    54,     0,    27,    53,    38,    54,
     0,    97,    59,   100,     0,    97,    59,    38,    53,    97,
    54,     0,   100,     0,    38,    53,    97,    54,     0,    53,
    98,    23,    98,    54,     0,    98,    23,    98,     0,    53,
    98,    24,    98,    54,     0,    98,    24,    98,     0,    53,
    25,    98,    54,     0,    44,     0,    25,    98,     0,    99,
     0,   100,    17,   100,     0,    53,   100,    17,   100,    54,
     0,   100,    18,   100,     0,    53,   100,    18,   100,    54,
     0,   100,    19,   100,     0,    53,   100,    19,   100,    54,
     0,   100,    21,   100,     0,    53,   100,    21,   100,    54,
     0,   100,    20,   100,     0,    53,   100,    20,   100,    54,
     0,   100,    22,   100,     0,    53,   100,    22,   100,    54,
     0,   100,     0,   100,    45,   100,     0,   100,    47,   100,
     0,   100,    48,   100,     0,   100,    46,   100,     0,   100,
    49,   100,     0,    53,   100,    54,     0,    46,   100,     0,
    38,     0,    43,     0,    42,     0,    41,     0,    38,    51,
    82,    52,     0,    38,    60,    38,     0,    38,    60,    96,
     0,    96,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    49,    56,    57,    61,    65,    66,    70,    71,    76,    84,
    95,    96,    99,   100,   105,   114,   121,   122,   126,   130,
   131,   136,   145,   152,   153,   157,   158,   163,   166,   172,
   173,   174,   177,   181,   182,   187,   191,   195,   200,   204,
   211,   212,   217,   218,   219,   220,   221,   225,   229,   233,
   237,   241,   245,   246,   250,   254,   258,   262,   263,   264,
   265,   269,   270,   273,   274,   275,   276,   277,   278,   279,
   280,   281,   285,   291,   292,   293,   298,   299,   300,   301,
   305,   306,   307,   308,   309,   310,   311,   312,   315,   316,
   317,   318,   319,   320,   321,   322,   323,   324,   325,   326,
   327,   331,   332,   333,   334,   335,   336,   337,   338,   339,
   340,   341,   342,   343,   344,   345
};

static const char * const yytname[] = {   "$","error","$illegal.","BGIN","END",
"ASSIGN","NR","BGINGLOBAL","ENDGLOBAL","BGINVARS","ENDVARS","BGINCLASS","ENDCLASS",
"BGINFUNC","ENDFUNC","CLASS","CONST","EQ","NEQ","GT","LT","GTE","LTE","AND",
"OR","NOT","PRINT","TYPEOF","EVAL","IF","ELSE","WHILE","FOR","DO","LOOP","BREAK",
"CONTINUE","RETURN","ID","TYPE","STRING","CHAR","FLOAT","INT","BOOL","'+'","'-'",
"'*'","'/'","'%'","'^'","'['","']'","'('","')'","';'","'{'","'}'","':'","','",
"'.'","progr","global_declarations","declarations","vars_declarations","decl_vars",
"decl_var","class_declarations","decl_classes","decl_class","@1","membs_list",
"class_memb","methods_list","method","@2","func_declarations","decl_funcs","def_func",
"@3","list_param","param","list_array","fblock","@4","main","@5","list","statement",
"@6","@7","@8","@9","@10","init_instante","assignment_stmt","call_func","call_list",
"bool_expr","expression","arithm_expr",""
};
#endif

static const short yyr1[] = {     0,
    61,    62,    62,    63,    64,    64,    65,    65,    66,    66,
    67,    67,    68,    68,    70,    69,    71,    71,    72,    73,
    73,    75,    74,    76,    76,    77,    77,    79,    78,    80,
    80,    80,    81,    82,    82,    84,    83,    83,    86,    85,
    87,    87,    88,    88,    88,    88,    89,    88,    90,    88,
    91,    88,    88,    92,    88,    93,    88,    88,    88,    88,
    88,    94,    94,    95,    95,    95,    95,    95,    95,    95,
    95,    95,    96,    96,    96,    96,    97,    97,    97,    97,
    98,    98,    98,    98,    98,    98,    98,    98,    99,    99,
    99,    99,    99,    99,    99,    99,    99,    99,    99,    99,
    99,   100,   100,   100,   100,   100,   100,   100,   100,   100,
   100,   100,   100,   100,   100,   100
};

static const short yyr2[] = {     0,
     2,     3,     0,     3,     3,     0,     2,     3,     2,     5,
     3,     0,     1,     2,     0,     8,     1,     2,     4,     2,
     0,     0,     9,     3,     0,     1,     2,     0,     9,     1,
     3,     0,     2,     3,     1,     0,     6,     0,     0,     4,
     2,     3,     1,     1,     2,     5,     0,     8,     0,    18,
     0,     8,     8,     0,     7,     0,    12,     1,     1,     1,
     2,     4,     5,     4,     4,     3,     3,     6,     6,     6,
     5,     5,     4,     3,     4,     4,     3,     6,     1,     4,
     5,     3,     5,     3,     4,     1,     2,     1,     3,     5,
     3,     5,     3,     5,     3,     5,     3,     5,     3,     5,
     1,     3,     3,     3,     3,     3,     3,     2,     1,     1,
     1,     1,     4,     3,     3,     1
};

static const short yydefact[] = {     3,
     6,     0,     0,     0,    12,    39,     1,     0,     0,     0,
     2,     0,    25,     0,     9,     5,     0,     7,     0,     0,
    13,     0,     4,     0,     0,     0,     0,     0,     0,     0,
    60,    59,     0,     0,     0,    44,     0,     0,    58,    43,
     0,     8,     0,    11,    14,     0,     0,    26,     0,     0,
     0,     0,     0,     0,     0,     0,   109,   112,   111,   110,
    86,     0,     0,   116,    61,    88,   101,     0,    45,     0,
     0,     0,     9,    40,     0,    41,    35,     0,    15,     0,
    24,    27,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    87,     0,     0,     0,   108,     0,     0,   101,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    67,    66,     0,     0,   109,    74,     0,    79,
     0,     0,    42,    10,     0,     0,    32,    75,    76,     0,
     0,     0,     0,     0,    54,     0,   114,   115,     0,    87,
     0,     0,     0,     0,     0,     0,     0,     0,   107,    82,
    84,    89,    91,    93,    97,    95,    99,   102,   105,   103,
   104,   106,     0,     0,     0,     0,    73,     0,     0,    65,
    64,    34,     0,    21,    17,     0,     0,    30,     0,    51,
     0,     0,     0,   113,    85,    82,    84,    89,    91,    93,
    97,    95,    99,     0,     0,    46,     0,     0,   109,    77,
    72,    71,     0,    18,     0,    33,     0,     0,     0,     0,
     0,     0,     0,     0,    81,    83,    90,    92,    94,    98,
    96,   100,     0,     0,    70,   116,    68,    73,     0,     0,
     0,     0,    20,    28,    31,     0,     0,     0,     0,     0,
    55,    62,     0,     0,    19,     0,    16,    38,     0,    48,
    52,     0,    53,    63,    73,    32,    36,     0,     0,    56,
     0,    38,    29,     0,     0,     0,     0,    49,     0,    22,
     0,     0,    57,    38,     0,     0,     0,    37,     0,    23,
     0,     0,     0,    50,     0,     0,     0
};

static const short yydefgoto[] = {   285,
     2,     4,     5,     9,    36,    13,    20,    21,   126,   174,
   175,   205,   233,   274,    23,    47,    48,   248,   177,   178,
    78,   258,   262,     7,    14,    37,    38,   210,   272,   211,
   183,   265,   164,    39,    64,   119,    65,    66,    67
};

static const short yypact[] = {    49,
    64,    92,    52,    98,    73,-32768,-32768,    59,    -1,    74,
-32768,    99,   120,   548,    93,-32768,   102,-32768,   116,   134,
-32768,   125,-32768,   115,   121,   126,   131,   133,   110,   150,
-32768,-32768,   425,    34,   161,-32768,   244,   159,-32768,-32768,
   162,-32768,   160,-32768,-32768,   177,     7,-32768,   141,   179,
   425,   425,   138,   548,   548,   425,    -3,-32768,-32768,-32768,
-32768,   129,   447,-32768,   128,-32768,   267,   477,   165,   162,
   456,   181,     2,-32768,   167,-32768,-32768,   -30,-32768,   172,
-32768,-32768,   173,   175,   -11,    -9,    28,   188,   184,   264,
   291,-32768,   162,    55,   129,   113,   425,   170,    91,   425,
   425,   129,   129,   129,   129,   129,   129,   129,   129,   129,
   129,   129,-32768,   259,   194,   -24,    45,-32768,   -10,   259,
   236,   486,-32768,-32768,   199,   206,   207,-32768,-32768,   193,
   196,   249,   425,   225,-32768,    31,   204,-32768,    72,   205,
   425,   425,   129,   129,   129,   129,   129,   129,-32768,-32768,
   237,   259,   259,   259,   259,   259,   259,   113,   113,-32768,
-32768,-32768,   256,    32,   269,   456,-32768,   525,   495,-32768,
   259,-32768,   234,   206,-32768,   271,    69,-32768,   548,-32768,
   -13,   241,   548,-32768,-32768,   257,   -18,   189,   218,   408,
   543,   553,   563,   129,   314,-32768,   516,    76,    81,   259,
-32768,   259,   294,-32768,    -5,-32768,   254,   207,   305,   548,
   548,   138,   425,   320,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   143,   129,-32768,   149,   259,-32768,   456,   280,
   307,   295,-32768,-32768,-32768,   344,   334,   349,   310,    -7,
-32768,-32768,   163,    88,-32768,   326,-32768,   337,   347,-32768,
-32768,   352,-32768,-32768,-32768,   207,-32768,   365,   548,-32768,
    89,   337,-32768,   363,   548,   376,   548,-32768,   378,-32768,
   382,   548,-32768,   337,   390,   392,   391,-32768,   428,-32768,
   403,   548,   407,-32768,   460,   461,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,-32768,    83,-32768,-32768,   445,-32768,-32768,
   296,-32768,-32768,-32768,-32768,-32768,   429,-32768,   219,   272,
   -62,  -242,-32768,-32768,-32768,   -52,   -36,-32768,-32768,-32768,
-32768,-32768,-32768,   -49,   -14,  -160,   -26,-32768,   -44
};


#define	YYLAST		617


static const short yytable[] = {    40,
    75,    90,    91,    89,   100,   198,   122,   116,    16,   100,
   101,   100,   101,   100,   101,   100,   101,    96,    99,   267,
    81,   124,    40,   114,    85,    86,   120,   165,   125,    92,
   136,   277,    68,   231,   125,   216,    98,     8,    68,    40,
    40,   212,   130,   167,   131,    46,   253,    93,   168,    71,
   139,   232,    41,    75,    75,     1,    94,   152,   153,   154,
   155,   156,   157,   158,   159,   160,   161,   162,   244,   195,
   140,    69,     3,   150,   151,    40,    40,   171,    70,   138,
    24,    25,   184,    12,    70,    10,    71,    72,   196,   125,
     8,    17,   137,    72,     6,    93,    15,   166,   188,   189,
   190,   191,   192,   193,    94,    11,   181,   143,   144,   145,
   146,   147,   148,    19,   186,   187,   108,   109,   110,   111,
   112,   120,   207,   200,   202,   149,   209,   208,    18,   228,
   214,    93,    22,   229,   168,   108,   109,   110,   111,   112,
    94,   255,   266,    41,   149,    44,   168,   208,    19,   223,
   100,   101,   227,    43,    24,    25,    42,   237,   238,   110,
   111,   112,   239,    46,    40,    54,    57,    49,    40,    58,
    59,    60,    75,    50,    62,    87,    88,    75,    51,   243,
    83,    95,   226,    52,   120,    53,   240,   108,   109,   110,
   111,   112,   141,   142,    40,    40,    40,   242,    73,    40,
    75,    75,   -69,   -69,    77,    55,   264,   108,   109,   110,
   111,   112,   269,    76,    80,    79,    84,   254,   121,   276,
   115,   123,    40,    40,   127,   132,   128,    75,   129,   283,
   271,   163,    75,   108,   109,   110,   111,   112,   133,    75,
   169,   172,   217,   173,    40,   176,    75,    74,   179,    40,
    40,   180,    40,   122,    40,   182,    71,    40,   185,   100,
   194,    40,   108,   109,   110,   111,   112,    40,    40,    24,
    25,   218,    26,   197,    27,    28,    29,    30,    31,    32,
    33,    34,    35,   102,   103,   104,   105,   106,   107,    24,
    25,   203,    26,   213,    27,    28,    29,    30,    31,    32,
    33,    34,    35,   108,   109,   110,   111,   112,   206,   234,
   215,   108,   109,   110,   111,   112,    24,    25,   224,    26,
   134,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    24,    25,   230,    26,   245,    27,    28,    29,    30,    31,
    32,    33,    34,    35,   246,    24,    25,   135,    26,   247,
    27,    28,    29,    30,    31,    32,    33,    34,    35,    24,
    25,   236,    26,   252,    27,    28,    29,    30,    31,    32,
    33,    34,    35,   249,    24,    25,   241,    26,   256,    27,
    28,    29,    30,    31,    32,    33,    34,    35,    24,    25,
   250,    26,   257,    27,    28,    29,    30,    31,    32,    33,
    34,    35,   259,    24,    25,   251,    26,   260,    27,    28,
    29,    30,    31,    32,    33,    34,    35,    24,    25,   268,
    26,   263,    27,    28,    29,    30,    31,    32,    33,    34,
    35,   270,    24,    25,   273,    26,   275,    27,    28,    29,
    30,    31,    32,    33,    34,    35,   278,   280,   279,    56,
    24,    25,   108,   109,   110,   111,   112,   281,   282,   286,
   287,   219,    57,   284,    45,    58,    59,    60,    61,   204,
    62,    97,    24,    25,   261,    82,     0,    63,     0,   235,
     0,    24,    25,     0,    57,     0,     0,    58,    59,    60,
    61,     0,    62,   117,     0,     0,    58,    59,    60,    63,
     0,    62,    24,    25,     0,     0,     0,     0,    95,   118,
     0,    24,    25,     0,    57,     0,   113,    58,    59,    60,
    24,    25,    62,    57,     0,   170,    58,    59,    60,    95,
     0,    62,    57,     0,   201,    58,    59,    60,    95,     0,
    62,    24,    25,     0,     0,     0,     0,    95,     0,     0,
    24,    25,     0,    57,     0,   225,    58,    59,    60,     0,
     0,    62,   199,     0,     0,    58,    59,    60,    95,     0,
    62,     0,     0,    24,    25,     0,    26,    95,    27,    28,
    29,    30,    31,    32,    33,    34,    35,   108,   109,   110,
   111,   112,     0,     0,     0,     0,   220,   108,   109,   110,
   111,   112,     0,     0,     0,     0,   221,   108,   109,   110,
   111,   112,     0,     0,     0,     0,   222
};

static const short yycheck[] = {    14,
    37,    54,    55,    53,    23,   166,     5,    70,    10,    23,
    24,    23,    24,    23,    24,    23,    24,    62,    63,   262,
    14,    52,    37,    68,    51,    52,    71,    52,    59,    56,
    93,   274,     5,    39,    59,    54,    63,    39,     5,    54,
    55,    55,    54,    54,    54,    39,    54,    51,    59,    53,
    95,    57,    51,    90,    91,     7,    60,   102,   103,   104,
   105,   106,   107,   108,   109,   110,   111,   112,   229,    38,
    97,    38,     9,   100,   101,    90,    91,   122,    51,    94,
    26,    27,    52,    11,    51,     3,    53,    60,    57,    59,
    39,     9,    38,    60,     3,    51,    38,    53,   143,   144,
   145,   146,   147,   148,    60,     8,   133,    17,    18,    19,
    20,    21,    22,    15,   141,   142,    45,    46,    47,    48,
    49,   166,    54,   168,   169,    54,   179,    59,    55,    54,
   183,    51,    13,    53,    59,    45,    46,    47,    48,    49,
    60,    54,    54,    51,    54,    12,    59,    59,    15,   194,
    23,    24,   197,    38,    26,    27,    55,   210,   211,    47,
    48,    49,   212,    39,   179,    56,    38,    53,   183,    41,
    42,    43,   209,    53,    46,    38,    39,   214,    53,   224,
    40,    53,   197,    53,   229,    53,   213,    45,    46,    47,
    48,    49,    23,    24,   209,   210,   211,    55,    38,   214,
   237,   238,    54,    55,    43,    56,   259,    45,    46,    47,
    48,    49,   265,    55,    38,    56,    38,    55,    38,   272,
    56,    55,   237,   238,    53,    38,    54,   264,    54,   282,
   267,    38,   269,    45,    46,    47,    48,    49,    55,   276,
     5,    43,    54,    38,   259,    39,   283,     4,    56,   264,
   265,    56,   267,     5,   269,    31,    53,   272,    54,    23,
     5,   276,    45,    46,    47,    48,    49,   282,   283,    26,
    27,    54,    29,     5,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    17,    18,    19,    20,    21,    22,    26,
    27,    58,    29,    53,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    45,    46,    47,    48,    49,    38,    56,
    54,    45,    46,    47,    48,    49,    26,    27,     5,    29,
    57,    31,    32,    33,    34,    35,    36,    37,    38,    39,
    26,    27,    39,    29,    55,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    38,    26,    27,    57,    29,    55,
    31,    32,    33,    34,    35,    36,    37,    38,    39,    26,
    27,    57,    29,    54,    31,    32,    33,    34,    35,    36,
    37,    38,    39,    30,    26,    27,    57,    29,    53,    31,
    32,    33,    34,    35,    36,    37,    38,    39,    26,    27,
    57,    29,    56,    31,    32,    33,    34,    35,    36,    37,
    38,    39,    56,    26,    27,    57,    29,    56,    31,    32,
    33,    34,    35,    36,    37,    38,    39,    26,    27,    57,
    29,    57,    31,    32,    33,    34,    35,    36,    37,    38,
    39,    56,    26,    27,    57,    29,    55,    31,    32,    33,
    34,    35,    36,    37,    38,    39,    57,    57,    57,    25,
    26,    27,    45,    46,    47,    48,    49,    30,    56,     0,
     0,    54,    38,    57,    20,    41,    42,    43,    44,   174,
    46,    25,    26,    27,   256,    47,    -1,    53,    -1,   208,
    -1,    26,    27,    -1,    38,    -1,    -1,    41,    42,    43,
    44,    -1,    46,    38,    -1,    -1,    41,    42,    43,    53,
    -1,    46,    26,    27,    -1,    -1,    -1,    -1,    53,    54,
    -1,    26,    27,    -1,    38,    -1,    40,    41,    42,    43,
    26,    27,    46,    38,    -1,    40,    41,    42,    43,    53,
    -1,    46,    38,    -1,    40,    41,    42,    43,    53,    -1,
    46,    26,    27,    -1,    -1,    -1,    -1,    53,    -1,    -1,
    26,    27,    -1,    38,    -1,    40,    41,    42,    43,    -1,
    -1,    46,    38,    -1,    -1,    41,    42,    43,    53,    -1,
    46,    -1,    -1,    26,    27,    -1,    29,    53,    31,    32,
    33,    34,    35,    36,    37,    38,    39,    45,    46,    47,
    48,    49,    -1,    -1,    -1,    -1,    54,    45,    46,    47,
    48,    49,    -1,    -1,    -1,    -1,    54,    45,    46,    47,
    48,    49,    -1,    -1,    -1,    -1,    54
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 49 "limbaj.y"
{ 
                                   if (errorCount == 0) 
                                       std::cout << "The program is correct!" << std::endl; 
                               ;
    break;}
case 9:
#line 76 "limbaj.y"
{
                                   if (!current->existsId(yyvsp[0].string)) {
                                       current->addVar(yyvsp[-1].string, yyvsp[0].string);
                                   } else {
                                       errorCount++; 
                                       yyerror(("Variable already defined at line: " + std::to_string(yylineno)).c_str());
                                   }
                               ;
    break;}
case 10:
#line 84 "limbaj.y"
{
                                   if (!current->existsId(yyvsp[-3].string)) {
                                       current->addVar(yyvsp[-4].string, yyvsp[-3].string);
                                   } else {
                                       errorCount++; 
                                       yyerror(("Variable already defined at line: " + std::to_string(yylineno)).c_str());
                                   }
                               ;
    break;}
case 15:
#line 105 "limbaj.y"
{
        // Creează tabelă pentru clasa curentă
        if (current->existsId(yyvsp[-1].string)) { // Verifică dacă clasa există deja
            errorCount++;
            yyerror(("Class already defined at line: " + std::to_string(yylineno)).c_str());
        } else {
            currentTable = new SymTable(yyvsp[-1].string, currentTable);  // Creează un nou tabel de simboluri pentru clasă
            tables.push_back(currentTable); // Adaugă în lista globală de tabele
        }
    ;
    break;}
case 16:
#line 114 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 22:
#line 136 "limbaj.y"
{
        // Verifică dacă funcția este deja definită
        if (currentTable->existsId(yyvsp[-4].string)) { 
            errorCount++;
            yyerror(("Function " + std::string(yyvsp[-4].string) + " already defined at line: " + std::to_string(yylineno)).c_str());
        } else {
            // Adaugă funcția în tabela simbolurilor a clasei
            currentTable->addFunc(yyvsp[-5].string, yyvsp[-4].string);
        }
    ;
    break;}
case 23:
#line 145 "limbaj.y"
{
        // Revenire la tabelul simbolurilor al clasei
        currentTable = currentTable->prev;
    ;
    break;}
case 28:
#line 163 "limbaj.y"
{
        currentTable = new SymTable(yyvsp[-4].string, currentTable); // Crează un tabel de simboluri pentru funcția curentă
        tables.push_back(currentTable);  // Adaugă tabelul global
    ;
    break;}
case 29:
#line 166 "limbaj.y"
{
        currentTable = currentTable->prev; // Revenire la scopul părinte
    ;
    break;}
case 36:
#line 187 "limbaj.y"
{
        // Creează un nou scop pentru acest bloc
        currentTable = new SymTable("block", currentTable);
        tables.push_back(currentTable); // Salvează tabelă în lista globală
    ;
    break;}
case 37:
#line 191 "limbaj.y"
{
        // Revenire la scopul părinte după încheierea blocului
        currentTable = currentTable->prev;
    ;
    break;}
case 39:
#line 200 "limbaj.y"
{ 
        // Creare tabelă pentru scopul main
        currentTable = new SymTable("main", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 40:
#line 204 "limbaj.y"
{
        // Revenire la scopul global
        currentTable = currentTable->prev;
    ;
    break;}
case 47:
#line 221 "limbaj.y"
{
        // Creează o tabelă pentru scopul IF
        currentTable = new SymTable("if", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 48:
#line 225 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 49:
#line 229 "limbaj.y"
{
        // Creează o tabelă pentru scopul IF
        currentTable = new SymTable("if", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 50:
#line 233 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 51:
#line 237 "limbaj.y"
{
        // Creează o tabelă pentru scopul WHILE
        currentTable = new SymTable("while", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 52:
#line 241 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 54:
#line 246 "limbaj.y"
{
        // Creează o tabelă pentru scopul LOOP
        currentTable = new SymTable("loop", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 55:
#line 250 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 56:
#line 254 "limbaj.y"
{
        // Creează o tabelă pentru scopul FOR
        currentTable = new SymTable("for", currentTable);
        tables.push_back(currentTable);
    ;
    break;}
case 57:
#line 258 "limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 73:
#line 285 "limbaj.y"
{
                               if (!current->existsId(yyvsp[-3].string)) { // Verifică dacă funcția există
                                   errorCount++;
                                   yyerror(("Function " + std::string(yyvsp[-3].string) + " not declared at line: " + std::to_string(yylineno)).c_str());
                               }
                           ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 350 "limbaj.y"

void yyerror(const char * s){
     cout << "error: " << s << " at line: " << yylineno << endl;
}

int main(int argc, char** argv) {
    yyin = fopen(argv[1], "r");
    current = new SymTable("global");
    tables.push_back(current);
    yyparse();

    std::cout << "Variables in global scope:" << std::endl;
    globalTable->printVars();

    // Eliberare memorie pentru toate tabelele
    for (SymTable* table : tables) {
        delete table;
    }

    if (errorCount > 0) {
        std::cout << "There were " << errorCount << " errors." << std::endl;
    } else {
        std::cout << "The program is correct!" << std::endl;
    }

    return 0;
}
