#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from src/limbaj.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "src/limbaj.y"

#include <iostream>
#include <vector>
#include "utils.h"
extern FILE* yyin;
extern char* yytext;
extern int yylineno;
extern int yylex();

int errorCount = 0;

#line 12 "src/limbaj.y"
typedef union 
{
     int number;
     float real_number;
     bool true_or_false;
     char caracter;
     char* string;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	BGIN	258
#define	END	259
#define	ASSIGN	260
#define	NR	261
#define	BGINGLOBAL	262
#define	ENDGLOBAL	263
#define	BGINVARS	264
#define	ENDVARS	265
#define	BGINCLASS	266
#define	ENDCLASS	267
#define	BGINFUNC	268
#define	ENDFUNC	269
#define	CLASS	270
#define	EQ	271
#define	NEQ	272
#define	GT	273
#define	LT	274
#define	GTE	275
#define	LTE	276
#define	AND	277
#define	OR	278
#define	NOT	279
#define	PRINT	280
#define	TYPEOF	281
#define	EVAL	282
#define	IF	283
#define	ELSE	284
#define	WHILE	285
#define	FOR	286
#define	DO	287
#define	LOOP	288
#define	BREAK	289
#define	CONTINUE	290
#define	RETURN	291
#define	ID	292
#define	SVAL	293
#define	CHAR	294
#define	STRING	295
#define	FLOAT	296
#define	INT	297
#define	BOOL	298
#define	FVAL	299
#define	IVAL	300
#define	BVAL	301
#define	CVAL	302


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int BGIN;
static const int END;
static const int ASSIGN;
static const int NR;
static const int BGINGLOBAL;
static const int ENDGLOBAL;
static const int BGINVARS;
static const int ENDVARS;
static const int BGINCLASS;
static const int ENDCLASS;
static const int BGINFUNC;
static const int ENDFUNC;
static const int CLASS;
static const int EQ;
static const int NEQ;
static const int GT;
static const int LT;
static const int GTE;
static const int LTE;
static const int AND;
static const int OR;
static const int NOT;
static const int PRINT;
static const int TYPEOF;
static const int EVAL;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int DO;
static const int LOOP;
static const int BREAK;
static const int CONTINUE;
static const int RETURN;
static const int ID;
static const int SVAL;
static const int CHAR;
static const int STRING;
static const int FLOAT;
static const int INT;
static const int BOOL;
static const int FVAL;
static const int IVAL;
static const int BVAL;
static const int CVAL;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,BGIN=258
	,END=259
	,ASSIGN=260
	,NR=261
	,BGINGLOBAL=262
	,ENDGLOBAL=263
	,BGINVARS=264
	,ENDVARS=265
	,BGINCLASS=266
	,ENDCLASS=267
	,BGINFUNC=268
	,ENDFUNC=269
	,CLASS=270
	,EQ=271
	,NEQ=272
	,GT=273
	,LT=274
	,GTE=275
	,LTE=276
	,AND=277
	,OR=278
	,NOT=279
	,PRINT=280
	,TYPEOF=281
	,EVAL=282
	,IF=283
	,ELSE=284
	,WHILE=285
	,FOR=286
	,DO=287
	,LOOP=288
	,BREAK=289
	,CONTINUE=290
	,RETURN=291
	,ID=292
	,SVAL=293
	,CHAR=294
	,STRING=295
	,FLOAT=296
	,INT=297
	,BOOL=298
	,FVAL=299
	,IVAL=300
	,BVAL=301
	,CVAL=302


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::BGIN=258;
const int YY_parse_CLASS::END=259;
const int YY_parse_CLASS::ASSIGN=260;
const int YY_parse_CLASS::NR=261;
const int YY_parse_CLASS::BGINGLOBAL=262;
const int YY_parse_CLASS::ENDGLOBAL=263;
const int YY_parse_CLASS::BGINVARS=264;
const int YY_parse_CLASS::ENDVARS=265;
const int YY_parse_CLASS::BGINCLASS=266;
const int YY_parse_CLASS::ENDCLASS=267;
const int YY_parse_CLASS::BGINFUNC=268;
const int YY_parse_CLASS::ENDFUNC=269;
const int YY_parse_CLASS::CLASS=270;
const int YY_parse_CLASS::EQ=271;
const int YY_parse_CLASS::NEQ=272;
const int YY_parse_CLASS::GT=273;
const int YY_parse_CLASS::LT=274;
const int YY_parse_CLASS::GTE=275;
const int YY_parse_CLASS::LTE=276;
const int YY_parse_CLASS::AND=277;
const int YY_parse_CLASS::OR=278;
const int YY_parse_CLASS::NOT=279;
const int YY_parse_CLASS::PRINT=280;
const int YY_parse_CLASS::TYPEOF=281;
const int YY_parse_CLASS::EVAL=282;
const int YY_parse_CLASS::IF=283;
const int YY_parse_CLASS::ELSE=284;
const int YY_parse_CLASS::WHILE=285;
const int YY_parse_CLASS::FOR=286;
const int YY_parse_CLASS::DO=287;
const int YY_parse_CLASS::LOOP=288;
const int YY_parse_CLASS::BREAK=289;
const int YY_parse_CLASS::CONTINUE=290;
const int YY_parse_CLASS::RETURN=291;
const int YY_parse_CLASS::ID=292;
const int YY_parse_CLASS::SVAL=293;
const int YY_parse_CLASS::CHAR=294;
const int YY_parse_CLASS::STRING=295;
const int YY_parse_CLASS::FLOAT=296;
const int YY_parse_CLASS::INT=297;
const int YY_parse_CLASS::BOOL=298;
const int YY_parse_CLASS::FVAL=299;
const int YY_parse_CLASS::IVAL=300;
const int YY_parse_CLASS::BVAL=301;
const int YY_parse_CLASS::CVAL=302;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		311
#define	YYFLAG		-32768
#define	YYNTBASE	64

#define YYTRANSLATE(x) ((unsigned)(x) <= 302 ? yytranslate[x] : 115)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    52,     2,     2,    56,
    57,    50,    48,    61,    49,    63,    51,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    62,    58,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    54,     2,    55,    53,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    59,     2,    60,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,     9,    10,    14,    18,    19,    22,    26,
    28,    30,    32,    34,    36,    38,    40,    42,    44,    46,
    49,    55,    58,    64,    66,    70,    72,    76,    77,    79,
    82,    83,    92,    94,    97,   102,   110,   117,   120,   121,
   122,   132,   136,   137,   139,   142,   143,   151,   152,   160,
   164,   166,   170,   171,   174,   180,   184,   186,   189,   190,
   191,   196,   198,   201,   204,   207,   210,   211,   221,   222,
   231,   232,   242,   243,   249,   250,   263,   266,   269,   273,
   274,   275,   281,   286,   292,   296,   297,   308,   314,   318,
   325,   327,   330,   335,   340,   344,   349,   354,   361,   367,
   371,   373,   379,   383,   389,   393,   398,   401,   403,   407,
   413,   417,   423,   427,   433,   437,   443,   447,   453,   457,
   463,   465,   467,   471,   474,   476,   478,   480,   482,   484,
   486,   491,   495,   497,   499,   503,   507,   511,   515
};

static const short yyrhs[] = {    65,
    93,     0,     0,     7,    66,    67,     8,     0,     0,    74,
    68,    83,     0,     9,    69,    10,     0,     0,    72,    58,
     0,    69,    72,    58,     0,    42,     0,    41,     0,    40,
     0,    43,     0,    39,     0,    42,     0,    41,     0,    40,
     0,    43,     0,    39,     0,    71,    37,     0,    71,    37,
    54,    91,    55,     0,    37,    37,     0,    37,    37,    59,
   104,    60,     0,   105,     0,    73,    61,   113,     0,   113,
     0,    11,    75,    12,     0,     0,    76,     0,    75,    76,
     0,     0,    15,    37,    59,    77,    78,    80,    60,    58,
     0,    79,     0,    78,    79,     0,    37,    62,    71,    58,
     0,    37,    54,    91,    55,    62,    71,    58,     0,    37,
    62,    71,     5,   113,    58,     0,    80,    81,     0,     0,
     0,    70,    37,    56,    89,    57,    59,    82,    92,    60,
     0,    13,    84,    14,     0,     0,    85,     0,    84,    85,
     0,     0,    70,    37,    56,    89,    57,    86,    88,     0,
     0,    70,    37,    56,    89,    57,    58,    87,     0,    59,
    92,    60,     0,    90,     0,    89,    61,    90,     0,     0,
    71,    37,     0,    71,    37,    54,    91,    55,     0,    45,
    61,    45,     0,    45,     0,    92,    96,     0,     0,     0,
     3,    94,    95,     4,     0,    96,     0,    95,    96,     0,
   108,    58,     0,   109,    58,     0,    72,    58,     0,     0,
    28,    97,    56,   111,    57,    59,    95,    60,   102,     0,
     0,    30,    98,    56,   111,    57,    59,    95,    60,     0,
     0,    32,    99,    59,    95,    60,    30,    56,   111,    57,
     0,     0,    33,   100,    59,    95,    60,     0,     0,    31,
   101,    56,   105,    58,   111,    58,   105,    57,    59,    95,
    60,     0,    35,    58,     0,    34,    58,     0,    36,   111,
    58,     0,     0,     0,    29,   103,    59,    95,    60,     0,
    37,     5,   113,    58,     0,   104,    37,     5,   113,    58,
     0,   107,     5,   111,     0,     0,    71,    37,    54,    91,
    55,   106,     5,    59,    73,    60,     0,   107,     5,    59,
    73,    60,     0,    37,    63,    37,     0,    37,    63,    37,
    54,    91,    55,     0,    37,     0,    71,    37,     0,    37,
    54,    91,    55,     0,    37,    56,   110,    57,     0,    37,
    56,    57,     0,    25,    56,   111,    57,     0,    26,    56,
   111,    57,     0,    37,    63,    37,    56,   110,    57,     0,
    37,    63,    37,    56,    57,     0,   110,    61,   113,     0,
   113,     0,    56,   111,    22,   111,    57,     0,   111,    22,
   111,     0,    56,   111,    23,   111,    57,     0,   111,    23,
   111,     0,    56,    24,   111,    57,     0,    24,   111,     0,
   113,     0,   113,    16,   113,     0,    56,   113,    16,   113,
    57,     0,   113,    17,   113,     0,    56,   113,    17,   113,
    57,     0,   113,    18,   113,     0,    56,   113,    18,   113,
    57,     0,   113,    20,   113,     0,    56,   113,    20,   113,
    57,     0,   113,    19,   113,     0,    56,   113,    19,   113,
    57,     0,   113,    21,   113,     0,    56,   113,    21,   113,
    57,     0,   114,     0,   112,     0,    56,   113,    57,     0,
    49,   113,     0,    37,     0,    45,     0,    44,     0,    47,
     0,    46,     0,    38,     0,    37,    54,    91,    55,     0,
    37,    63,    37,     0,   109,     0,   108,     0,   113,    48,
   113,     0,   113,    50,   113,     0,   113,    51,   113,     0,
   113,    49,   113,     0,   113,    52,   113,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    44,    48,    53,    54,    58,    62,    63,    67,    68,    71,
    75,    79,    83,    87,    93,    97,   101,   105,   109,   116,
   117,   118,   119,   120,   123,   124,   128,   129,   132,   133,
   138,   153,   161,   162,   166,   170,   174,   186,   187,   192,
   209,   220,   221,   225,   226,   230,   242,   246,   256,   262,
   265,   269,   273,   277,   283,   292,   293,   297,   298,   302,
   307,   315,   316,   321,   322,   323,   324,   328,   335,   339,
   344,   348,   353,   357,   362,   366,   371,   372,   373,   376,
   377,   381,   389,   390,   393,   402,   407,   414,   423,   430,
   438,   443,   449,   458,   463,   468,   469,   472,   478,   486,
   491,   499,   500,   501,   502,   503,   508,   513,   516,   517,
   518,   519,   520,   521,   522,   523,   524,   525,   526,   527,
   530,   531,   532,   533,   534,   541,   546,   551,   556,   561,
   566,   574,   583,   587,   594,   595,   596,   597,   598
};

static const char * const yytname[] = {   "$","error","$illegal.","BGIN","END",
"ASSIGN","NR","BGINGLOBAL","ENDGLOBAL","BGINVARS","ENDVARS","BGINCLASS","ENDCLASS",
"BGINFUNC","ENDFUNC","CLASS","EQ","NEQ","GT","LT","GTE","LTE","AND","OR","NOT",
"PRINT","TYPEOF","EVAL","IF","ELSE","WHILE","FOR","DO","LOOP","BREAK","CONTINUE",
"RETURN","ID","SVAL","CHAR","STRING","FLOAT","INT","BOOL","FVAL","IVAL","BVAL",
"CVAL","'+'","'-'","'*'","'/'","'%'","'^'","'['","']'","'('","')'","';'","'{'",
"'}'","','","':'","'.'","progr","global_declarations","@1","declarations","vars_declarations",
"decl_vars","F_TYPE","V_TYPE","decl_var","init_list","class_declarations","decl_classes",
"decl_class","@2","membs_list","class_memb","methods_list","method","@3","func_declarations",
"decl_funcs","def_func","@4","@5","function_definition","list_param","param",
"list_array","fblock","main","@6","list","statement","@7","@8","@9","@10","@11",
"else_statement","@12","init_instante","assignment_stmt","@13","left_hand_side",
"call_func","call_method","call_list","bool_expr","logical_expr","expr","arithm_expr",
""
};
#endif

static const short yyr1[] = {     0,
    64,    66,    65,    65,    67,    68,    68,    69,    69,    70,
    70,    70,    70,    70,    71,    71,    71,    71,    71,    72,
    72,    72,    72,    72,    73,    73,    74,    74,    75,    75,
    77,    76,    78,    78,    79,    79,    79,    80,    80,    82,
    81,    83,    83,    84,    84,    86,    85,    87,    85,    88,
    89,    89,    89,    90,    90,    91,    91,    92,    92,    94,
    93,    95,    95,    96,    96,    96,    97,    96,    98,    96,
    99,    96,   100,    96,   101,    96,    96,    96,    96,   102,
   103,   102,   104,   104,   105,   106,   105,   105,   107,   107,
   107,   107,   107,   108,   108,   108,   108,   109,   109,   110,
   110,   111,   111,   111,   111,   111,   111,   111,   112,   112,
   112,   112,   112,   112,   112,   112,   112,   112,   112,   112,
   113,   113,   113,   113,   113,   113,   113,   113,   113,   113,
   113,   113,   113,   113,   114,   114,   114,   114,   114
};

static const short yyr2[] = {     0,
     2,     0,     4,     0,     3,     3,     0,     2,     3,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     2,
     5,     2,     5,     1,     3,     1,     3,     0,     1,     2,
     0,     8,     1,     2,     4,     7,     6,     2,     0,     0,
     9,     3,     0,     1,     2,     0,     7,     0,     7,     3,
     1,     3,     0,     2,     5,     3,     1,     2,     0,     0,
     4,     1,     2,     2,     2,     2,     0,     9,     0,     8,
     0,     9,     0,     5,     0,    12,     2,     2,     3,     0,
     0,     5,     4,     5,     3,     0,    10,     5,     3,     6,
     1,     2,     4,     4,     3,     4,     4,     6,     5,     3,
     1,     5,     3,     5,     3,     4,     2,     1,     3,     5,
     3,     5,     3,     5,     3,     5,     3,     5,     3,     5,
     1,     1,     3,     2,     1,     1,     1,     1,     1,     1,
     4,     3,     1,     1,     3,     3,     3,     3,     3
};

static const short yydefact[] = {     4,
     2,     0,    28,    60,     1,     0,     0,     7,     0,     0,
     0,    29,     3,     0,    43,     0,     0,    67,    69,    75,
    71,    73,     0,     0,     0,    91,    19,    17,    16,    15,
    18,     0,     0,     0,    62,    24,     0,     0,     0,     0,
    27,    30,    91,     0,     0,     0,     5,     0,     0,     0,
     0,     0,     0,     0,    78,    77,     0,   125,   130,   127,
   126,   129,   128,     0,     0,   134,   133,     0,   122,   108,
   121,    22,     0,     0,     0,    20,    66,    61,    63,     0,
    64,    65,    31,     0,     6,     0,     8,    14,    12,    11,
    10,    13,     0,     0,    44,     0,     0,     0,     0,     0,
     0,     0,   107,     0,     0,     0,   124,     0,     0,   108,
     0,     0,    79,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    57,     0,    95,     0,   101,
    89,     0,     0,    85,     0,    89,     9,     0,    42,    45,
    96,    97,     0,     0,    91,     0,     0,     0,     0,     0,
   132,     0,   107,     0,     0,     0,     0,     0,     0,     0,
     0,   123,   103,   105,   109,   111,   113,   117,   115,   119,
   135,   138,   136,   137,   139,     0,     0,     0,    93,    94,
     0,     0,     0,     0,     0,    26,     0,    39,    33,    53,
     0,     0,    92,     0,     0,    74,   131,   106,   103,   105,
   109,   111,   113,   117,   115,   119,     0,     0,    23,    56,
   100,     0,    99,     0,    21,    88,     0,     0,     0,    34,
     0,     0,     0,    51,     0,     0,     0,     0,     0,   102,
   104,   110,   112,   114,   118,   116,   120,     0,     0,    90,
    98,     0,    25,     0,     0,     0,     0,    38,    54,    46,
     0,     0,     0,     0,     0,     0,    83,     0,     0,     0,
     0,    35,    32,     0,     0,    48,     0,    52,    80,    70,
    86,     0,     0,    84,     0,     0,     0,    53,     0,    49,
    59,    47,    81,    68,     0,    72,     0,     0,    37,     0,
    55,     0,     0,     0,    87,    36,     0,    50,    58,     0,
     0,    40,     0,    76,    59,    82,     0,    41,     0,     0,
     0
};

static const short yydefgoto[] = {   309,
     2,     3,     7,    15,    44,    93,    32,    33,   185,     8,
    11,    12,   135,   188,   189,   221,   248,   305,    47,    94,
    95,   267,   280,   282,   223,   224,   127,   292,     5,     9,
    34,    35,    50,    51,    53,    54,    52,   284,   293,   177,
    36,   242,    37,    66,    67,   129,    68,    69,    70,    71
};

static const short yypact[] = {    31,
-32768,    49,    58,-32768,-32768,    74,    87,    98,   619,    83,
    59,-32768,-32768,   541,   124,    82,    93,-32768,-32768,-32768,
-32768,-32768,    89,   100,   517,   523,-32768,-32768,-32768,-32768,
-32768,   129,   111,   300,-32768,-32768,   165,   114,   115,   119,
-32768,-32768,   -17,   122,   121,   273,-32768,   517,   517,   125,
   134,   143,   132,   142,-32768,-32768,   517,   -35,-32768,-32768,
-32768,-32768,-32768,   592,   550,-32768,-32768,   -11,-32768,   328,
-32768,   144,   160,   564,   169,    -1,-32768,-32768,-32768,   151,
-32768,-32768,-32768,   172,-32768,   153,-32768,-32768,-32768,-32768,
-32768,-32768,   176,   198,-32768,    11,    13,   517,   517,   664,
   619,   619,-32768,   160,   177,   592,    91,   517,    22,   302,
   517,   517,-32768,   592,   592,   592,   592,   592,   592,   592,
   592,   592,   592,   592,   178,   166,   173,-32768,    -6,   328,
    92,   160,   592,   108,   192,   126,-32768,   186,-32768,-32768,
-32768,-32768,    20,    61,    42,   208,   188,   330,   361,   195,
   191,   302,   194,   517,   517,   592,   592,   592,   592,   592,
   592,-32768,-32768,   230,   519,   519,   333,   333,   333,   333,
    91,    91,-32768,-32768,-32768,   253,   -31,   216,-32768,-32768,
   592,   160,   578,   214,   -34,   328,   -30,   192,-32768,   669,
   201,   212,   218,   517,   251,-32768,-32768,-32768,   225,    18,
    60,   205,   615,   625,   635,   645,   592,   279,-32768,-32768,
   328,   231,-32768,    33,   282,-32768,   592,   160,   669,-32768,
   505,   252,    62,-32768,   619,   619,   160,    -8,   237,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   135,   592,-32768,
-32768,   290,   328,   245,    -2,   243,   265,-32768,   270,   247,
   669,   383,   405,   272,   664,   517,-32768,   215,   298,   244,
   592,-32768,-32768,   312,   160,-32768,   315,-32768,   309,-32768,
-32768,   318,    65,-32768,   592,   669,   259,   669,   274,-32768,
-32768,-32768,-32768,-32768,   329,-32768,    53,   341,-32768,    64,
-32768,   427,   346,   619,-32768,-32768,   347,-32768,-32768,   619,
   449,-32768,   471,-32768,-32768,-32768,   493,-32768,   407,   410,
-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,-32768,-32768,   206,   -84,     4,   137,-32768,
-32768,   417,-32768,-32768,   241,-32768,-32768,-32768,-32768,-32768,
   338,-32768,-32768,-32768,   156,   199,   -91,   146,-32768,-32768,
   -92,   -33,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   -98,-32768,-32768,    -9,    -4,   266,   -26,-32768,   -57,-32768
};


#define	YYLAST		712


static const short yytable[] = {    38,
    79,   147,   261,   -92,    39,   208,   107,   110,   148,   149,
   111,   112,   150,   111,   112,   146,   130,    45,   104,    72,
    74,    96,    97,   218,    38,   216,   217,   105,   209,    39,
   103,   219,   111,   112,   111,   112,    73,     1,   109,   111,
   184,   111,   112,   154,   155,    84,   113,    86,   152,   255,
   180,     4,   132,   134,   181,   262,   165,   166,   167,   168,
   169,   170,   171,   172,   173,   174,   175,   141,     6,   142,
    41,   143,   144,    10,   231,   186,   191,   116,   117,   118,
   119,   153,   111,   112,   163,   164,   111,   112,    10,   241,
   212,    38,    38,   181,    13,    73,    39,    39,   201,   202,
   203,   204,   205,   206,    84,   222,    14,   120,   121,   122,
   123,   124,   295,   217,    79,    79,   232,   192,   250,    40,
   297,   286,   251,   211,   251,   130,   244,   199,   200,   111,
   112,    85,   252,   253,   245,   254,    46,    48,    38,    38,
   122,   123,   124,    39,    39,   182,    55,   183,    49,   238,
   114,   115,   116,   117,   118,   119,   272,    56,    43,   243,
    27,    28,    29,    30,    31,    76,   222,   228,    77,    80,
   146,    81,    82,   279,    57,    16,    17,    83,    87,   182,
    98,   258,   120,   121,   122,   123,   124,    58,    59,    99,
   101,   288,   257,   222,    60,    61,    62,    63,   100,    64,
   102,   301,   125,   277,   126,   131,    65,   303,   136,   133,
   137,   139,   138,   151,   176,    38,    38,   186,    79,    79,
    39,    39,   116,   117,   118,   119,   178,   179,   187,   273,
   114,   115,   116,   117,   118,   119,    88,    89,    90,    91,
    92,   190,    38,    38,   193,   194,   183,    39,    39,   197,
   198,   111,   120,   121,   122,   123,   124,   207,   299,   225,
   210,   233,   120,   121,   122,   123,   124,    79,   215,    79,
   226,   227,   274,   299,   114,   115,   116,   117,   118,   119,
   229,   230,    38,   239,    38,   240,   -86,    39,   249,    39,
    38,    38,   256,    38,   259,    39,    39,    38,    39,   260,
   263,   264,    39,    78,   266,   276,   120,   121,   122,   123,
   124,    88,    89,    90,    91,    92,   289,   156,   157,   158,
   159,   160,   161,   265,    16,    17,   271,    18,   291,    19,
    20,    21,    22,    23,    24,    25,    26,   283,    27,    28,
    29,    30,    31,   114,   115,   116,   117,   118,   119,   120,
   121,   122,   123,   124,    16,    17,   275,    18,   162,    19,
    20,    21,    22,    23,    24,    25,    26,   278,    27,    28,
    29,    30,    31,   281,   285,   120,   121,   122,   123,   124,
   120,   121,   122,   123,   124,    16,    17,   294,    18,   195,
    19,    20,    21,    22,    23,    24,    25,    26,   296,    27,
    28,    29,    30,    31,   300,   302,   310,    16,    17,   311,
    18,   287,    19,    20,    21,    22,    23,    24,    25,    26,
   196,    27,    28,    29,    30,    31,   247,    42,   220,    16,
    17,   140,    18,   290,    19,    20,    21,    22,    23,    24,
    25,    26,   269,    27,    28,    29,    30,    31,   214,   268,
   307,    16,    17,     0,    18,     0,    19,    20,    21,    22,
    23,    24,    25,    26,   270,    27,    28,    29,    30,    31,
     0,     0,     0,    16,    17,     0,    18,     0,    19,    20,
    21,    22,    23,    24,    25,    26,   298,    27,    28,    29,
    30,    31,     0,     0,     0,    16,    17,     0,    18,     0,
    19,    20,    21,    22,    23,    24,    25,    26,   304,    27,
    28,    29,    30,    31,     0,     0,     0,    16,    17,     0,
    18,     0,    19,    20,    21,    22,    23,    24,    25,    26,
   306,    27,    28,    29,    30,    31,   116,   117,   118,   119,
    57,    16,    17,    88,    89,    90,    91,    92,     0,     0,
     0,     0,   308,    58,    59,     0,     0,     0,     0,    72,
    60,    61,    62,    63,   246,    64,   120,   121,   122,   123,
   124,     0,    65,   108,    16,    17,    73,    43,    74,    27,
    28,    29,    30,    31,     0,    75,    58,    59,    16,    17,
     0,     0,     0,    60,    61,    62,    63,     0,    64,     0,
    58,    59,    16,    17,     0,    65,     0,    60,    61,    62,
    63,     0,    64,     0,    58,    59,    16,    17,     0,   106,
   128,    60,    61,    62,    63,     0,    64,     0,    58,    59,
     0,     0,     0,   106,   213,    60,    61,    62,    63,     0,
    64,     0,     0,    16,    17,     0,    18,   106,    19,    20,
    21,    22,    23,    24,    25,    26,     0,    27,    28,    29,
    30,    31,   120,   121,   122,   123,   124,     0,     0,     0,
     0,   234,   120,   121,   122,   123,   124,     0,     0,     0,
     0,   235,   120,   121,   122,   123,   124,     0,     0,     0,
     0,   236,   120,   121,   122,   123,   124,     0,     0,     0,
   145,   237,    27,    28,    29,    30,    31,    27,    28,    29,
    30,    31
};

static const short yycheck[] = {     9,
    34,   100,     5,     5,     9,    37,    64,    65,   101,   102,
    22,    23,   104,    22,    23,   100,    74,    14,    54,    37,
    56,    48,    49,    54,    34,    60,    61,    63,    60,    34,
    57,    62,    22,    23,    22,    23,    54,     7,    65,    22,
   132,    22,    23,    22,    23,    63,    58,    44,   106,    58,
    57,     3,    54,    80,    61,    58,   114,   115,   116,   117,
   118,   119,   120,   121,   122,   123,   124,    57,    11,    57,
    12,    98,    99,    15,    57,   133,    57,    18,    19,    20,
    21,   108,    22,    23,   111,   112,    22,    23,    15,    57,
   182,   101,   102,    61,     8,    54,   101,   102,   156,   157,
   158,   159,   160,   161,    63,   190,     9,    48,    49,    50,
    51,    52,    60,    61,   148,   149,    57,    57,    57,    37,
    57,    57,    61,   181,    61,   183,   218,   154,   155,    22,
    23,    10,   225,   226,   219,   227,    13,    56,   148,   149,
    50,    51,    52,   148,   149,    54,    58,    56,    56,   207,
    16,    17,    18,    19,    20,    21,   255,    58,    37,   217,
    39,    40,    41,    42,    43,    37,   251,   194,    58,     5,
   255,    58,    58,   265,    24,    25,    26,    59,    58,    54,
    56,   239,    48,    49,    50,    51,    52,    37,    38,    56,
    59,   276,    58,   278,    44,    45,    46,    47,    56,    49,
    59,   294,    59,   261,    45,    37,    56,   300,    37,    59,
    58,    14,    37,    37,    37,   225,   226,   275,   252,   253,
   225,   226,    18,    19,    20,    21,    61,    55,    37,   256,
    16,    17,    18,    19,    20,    21,    39,    40,    41,    42,
    43,    56,   252,   253,    37,    58,    56,   252,   253,    55,
    57,    22,    48,    49,    50,    51,    52,     5,   292,    59,
    45,    57,    48,    49,    50,    51,    52,   301,    55,   303,
    59,    54,    58,   307,    16,    17,    18,    19,    20,    21,
    30,    57,   292,     5,   294,    55,     5,   292,    37,   294,
   300,   301,    56,   303,     5,   300,   301,   307,   303,    55,
    58,    37,   307,     4,    58,    62,    48,    49,    50,    51,
    52,    39,    40,    41,    42,    43,    58,    16,    17,    18,
    19,    20,    21,    54,    25,    26,    55,    28,    55,    30,
    31,    32,    33,    34,    35,    36,    37,    29,    39,    40,
    41,    42,    43,    16,    17,    18,    19,    20,    21,    48,
    49,    50,    51,    52,    25,    26,    59,    28,    57,    30,
    31,    32,    33,    34,    35,    36,    37,    56,    39,    40,
    41,    42,    43,    59,    57,    48,    49,    50,    51,    52,
    48,    49,    50,    51,    52,    25,    26,    59,    28,    60,
    30,    31,    32,    33,    34,    35,    36,    37,    58,    39,
    40,    41,    42,    43,    59,    59,     0,    25,    26,     0,
    28,   275,    30,    31,    32,    33,    34,    35,    36,    37,
    60,    39,    40,    41,    42,    43,   221,    11,   188,    25,
    26,    94,    28,   278,    30,    31,    32,    33,    34,    35,
    36,    37,    60,    39,    40,    41,    42,    43,   183,   251,
   305,    25,    26,    -1,    28,    -1,    30,    31,    32,    33,
    34,    35,    36,    37,    60,    39,    40,    41,    42,    43,
    -1,    -1,    -1,    25,    26,    -1,    28,    -1,    30,    31,
    32,    33,    34,    35,    36,    37,    60,    39,    40,    41,
    42,    43,    -1,    -1,    -1,    25,    26,    -1,    28,    -1,
    30,    31,    32,    33,    34,    35,    36,    37,    60,    39,
    40,    41,    42,    43,    -1,    -1,    -1,    25,    26,    -1,
    28,    -1,    30,    31,    32,    33,    34,    35,    36,    37,
    60,    39,    40,    41,    42,    43,    18,    19,    20,    21,
    24,    25,    26,    39,    40,    41,    42,    43,    -1,    -1,
    -1,    -1,    60,    37,    38,    -1,    -1,    -1,    -1,    37,
    44,    45,    46,    47,    60,    49,    48,    49,    50,    51,
    52,    -1,    56,    24,    25,    26,    54,    37,    56,    39,
    40,    41,    42,    43,    -1,    63,    37,    38,    25,    26,
    -1,    -1,    -1,    44,    45,    46,    47,    -1,    49,    -1,
    37,    38,    25,    26,    -1,    56,    -1,    44,    45,    46,
    47,    -1,    49,    -1,    37,    38,    25,    26,    -1,    56,
    57,    44,    45,    46,    47,    -1,    49,    -1,    37,    38,
    -1,    -1,    -1,    56,    57,    44,    45,    46,    47,    -1,
    49,    -1,    -1,    25,    26,    -1,    28,    56,    30,    31,
    32,    33,    34,    35,    36,    37,    -1,    39,    40,    41,
    42,    43,    48,    49,    50,    51,    52,    -1,    -1,    -1,
    -1,    57,    48,    49,    50,    51,    52,    -1,    -1,    -1,
    -1,    57,    48,    49,    50,    51,    52,    -1,    -1,    -1,
    -1,    57,    48,    49,    50,    51,    52,    -1,    -1,    -1,
    37,    57,    39,    40,    41,    42,    43,    39,    40,    41,
    42,    43
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 2:
#line 49 "src/limbaj.y"
{
                                    currentTable = globalTable; //avem tabelul currentTable pe care îl punem în lista de tabele
                                    tables.push_back(globalTable);
                                ;
    break;}
case 10:
#line 72 "src/limbaj.y"
{
            currentFunction.returnType = TYPE_INT;
        ;
    break;}
case 11:
#line 76 "src/limbaj.y"
{
            currentFunction.returnType = TYPE_FLOAT;
        ;
    break;}
case 12:
#line 80 "src/limbaj.y"
{
            currentFunction.returnType = TYPE_STRING;
        ;
    break;}
case 13:
#line 84 "src/limbaj.y"
{
            currentFunction.returnType = TYPE_BOOL;
        ;
    break;}
case 14:
#line 88 "src/limbaj.y"
{
            currentFunction.returnType = TYPE_CHAR;
        ;
    break;}
case 15:
#line 94 "src/limbaj.y"
{
            currentVariable.type.typeName = TYPE_INT;
        ;
    break;}
case 16:
#line 98 "src/limbaj.y"
{
            currentVariable.type.typeName = TYPE_FLOAT;
        ;
    break;}
case 17:
#line 102 "src/limbaj.y"
{
            currentVariable.type.typeName = TYPE_STRING;
        ;
    break;}
case 18:
#line 106 "src/limbaj.y"
{
            currentVariable.type.typeName = TYPE_BOOL;
        ;
    break;}
case 19:
#line 110 "src/limbaj.y"
{
            currentVariable.type.typeName = TYPE_CHAR;
        ;
    break;}
case 20:
#line 116 "src/limbaj.y"
{ exists_or_add(yyvsp[0].string, false); ;
    break;}
case 21:
#line 117 "src/limbaj.y"
{ exists_or_add(yyvsp[-3].string, true); ;
    break;}
case 22:
#line 118 "src/limbaj.y"
{ exists_or_add_for_custom_type(yyvsp[0].string, yyvsp[-1].string); ;
    break;}
case 23:
#line 119 "src/limbaj.y"
{ exists_or_add_for_custom_type(yyvsp[-3].string, yyvsp[-4].string); ;
    break;}
case 25:
#line 123 "src/limbaj.y"
{ArrayInitialization.push_back(stiva.back()); stiva.pop_back();;
    break;}
case 26:
#line 124 "src/limbaj.y"
{ArrayInitialization.push_back(stiva.back()); stiva.pop_back();;
    break;}
case 31:
#line 139 "src/limbaj.y"
{
        // Creează tabelă pentru clasa curentă
        if (currentTable->existsClass(yyvsp[-1].string)) 
        { // Verifică dacă clasa există deja
            errorCount++;
            yyerror(("Clasa a fost deja definită la linia: " + std::to_string(yylineno)).c_str());
        } 
        else 
        {
            currentClass.name = yyvsp[-1].string;
            currentTable->addClass(yyvsp[-1].string);
            currentTable = new SymTable(yyvsp[-1].string, currentTable);// Creează un nou tabel de simboluri pentru clasă
            tables.push_back(currentTable); // Adaugă în lista globală de tabele
        }
    ;
    break;}
case 32:
#line 154 "src/limbaj.y"
{
        // Revenire la scopul părinte
        currentTable = currentTable->prev;
    ;
    break;}
case 35:
#line 167 "src/limbaj.y"
{
                                    exists_or_add(yyvsp[-3].string, false);
                               ;
    break;}
case 36:
#line 171 "src/limbaj.y"
{
                                    exists_or_add(yyvsp[-6].string, true);
                               ;
    break;}
case 37:
#line 175 "src/limbaj.y"
{
                                    exists_or_add(yyvsp[-5].string, false);
                                    modifiedVariable = &currentTable->ids[yyvsp[-5].string];
                                    expr1 = stiva.back();
                                    SetNewValue(modifiedVariable, expr1);
                                    //cout << modifiedVariable->value.toString() << endl;
                                    //cout << currentTable->ids[$1].value.toString() << endl;
                                    stiva.pop_back();
                               ;
    break;}
case 40:
#line 193 "src/limbaj.y"
{
        // Verifică dacă funcția este deja definită
        if (currentTable->existsFunc(yyvsp[-4].string)) 
        { 
            errorCount++;
            yyerror(("Metoda " + std::string(yyvsp[-4].string) + " a fost deja definită la linia: " + std::to_string(yylineno)).c_str());
        } 
        else 
        {
            // Adaugă funcția în tabela de simboluri a clasei
            currentTable->addFunc(currentFunction.returnType, yyvsp[-4].string, currentParams, currentClass.name);
            currentTable = new SymTable(yyvsp[-4].string, currentTable);  // Creează un nou tabel de simboluri pentru clasă
            tables.push_back(currentTable);
            //currentParams.clear();
        }
    ;
    break;}
case 41:
#line 210 "src/limbaj.y"
{
        // Revenire la tabelul simbolurilor al clasei
        currentTable = currentTable->prev;
        //stergerea parametrilor
        currentParams.clear();
        ///pentru a nu se adăuga toți param. declarați vreodată în currentParams.
    ;
    break;}
case 46:
#line 231 "src/limbaj.y"
{   
                                        if(!currentTable->existsFunc(yyvsp[-3].string)) 
                                        {
                                            currentTable->addFunc(currentFunction.returnType, yyvsp[-3].string, currentParams);
                                        }

                                        currentTable = new SymTable(yyvsp[-3].string, currentTable); // Crează un tabel de simboluri pentru funcția curentă
                                        tables.push_back(currentTable);  // Adaugă tabelul global
                                        currentFunction.name = yyvsp[-3].string; 
                                    ;
    break;}
case 47:
#line 242 "src/limbaj.y"
{
                                        currentParams.clear();
                                        currentTable = currentTable->prev; // Revenire la scopul părinte
                                    ;
    break;}
case 48:
#line 247 "src/limbaj.y"
{
                                        if(!currentTable->existsFunc(yyvsp[-4].string)) 
                                        {
                                            currentTable->addFunc(currentFunction.returnType, yyvsp[-4].string, currentParams);
                                        }
                                        currentTable = new SymTable(yyvsp[-4].string, currentTable); // Crează un tabel de simboluri pentru funcția curentă
                                        tables.push_back(currentTable);  // Adaugă tabelul global
                                    ;
    break;}
case 49:
#line 256 "src/limbaj.y"
{
                                        currentParams.clear();
                                        currentTable = currentTable->prev; // Revenire la scopul părinte
                                    ;
    break;}
case 51:
#line 266 "src/limbaj.y"
{
                    currentParams.push_back(currentVariable);
                ;
    break;}
case 52:
#line 270 "src/limbaj.y"
{
                    currentParams.push_back(currentVariable);
                ;
    break;}
case 54:
#line 278 "src/limbaj.y"
{
                                    currentVariable.name = yyvsp[0].string;
                                    currentVariable.type.isArray = false;
                                    
                                ;
    break;}
case 55:
#line 284 "src/limbaj.y"
{
                                    currentVariable.name = yyvsp[-3].string;
                                    currentVariable.type.isArray = true;
                                ;
    break;}
case 56:
#line 292 "src/limbaj.y"
{currentArraySizes.push_back(yyvsp[0].number);currentArraySizes.push_back(yyvsp[-2].number);
    break;}
case 57:
#line 293 "src/limbaj.y"
{ currentArraySizes.push_back(yyvsp[0].number);
    break;}
case 60:
#line 303 "src/limbaj.y"
{ 
            // Creare tabelă pentru scopul main
            currentTable = new SymTable("main", currentTable);
            tables.push_back(currentTable);
        ;
    break;}
case 61:
#line 308 "src/limbaj.y"
{
            // Revenire la scopul global
            currentTable = currentTable->prev;
        ;
    break;}
case 67:
#line 325 "src/limbaj.y"
{
            addScopeName("if");
        ;
    break;}
case 68:
#line 330 "src/limbaj.y"
{  
            // Revenire la scopul părinte
            scopeStack.pop();
            currentTable = currentTable->prev;
        ;
    break;}
case 69:
#line 336 "src/limbaj.y"
{
            addScopeName("while");
        ;
    break;}
case 70:
#line 340 "src/limbaj.y"
{
            scopeStack.pop();
            currentTable = currentTable->prev;
        ;
    break;}
case 71:
#line 345 "src/limbaj.y"
{
            addScopeName("do-while");
        ;
    break;}
case 72:
#line 349 "src/limbaj.y"
{
            scopeStack.pop();
            currentTable = currentTable->prev;
        ;
    break;}
case 73:
#line 354 "src/limbaj.y"
{
            addScopeName("loop");
        ;
    break;}
case 74:
#line 358 "src/limbaj.y"
{
            scopeStack.pop();
            currentTable = currentTable->prev;
        ;
    break;}
case 75:
#line 363 "src/limbaj.y"
{
            addScopeName("for");
        ;
    break;}
case 76:
#line 367 "src/limbaj.y"
{
            scopeStack.pop();
            currentTable = currentTable->prev;
        ;
    break;}
case 81:
#line 378 "src/limbaj.y"
{
                    addScopeName("else");
                ;
    break;}
case 82:
#line 382 "src/limbaj.y"
{
                    scopeStack.pop();
                    currentTable = currentTable->prev;
                ;
    break;}
case 85:
#line 394 "src/limbaj.y"
{
                                    if(FindToBeModifiedVar(variableToAssign)) {
                                        expr1 = stiva.back();
                                        SetNewValue(modifiedVariable, expr1);
                                    }

                                    stiva.pop_back();
                                ;
    break;}
case 86:
#line 403 "src/limbaj.y"
{
                                    variableToAssign.varName = yyvsp[-3].string;
                                    variableToAssign.varType = 0;
                                    exists_or_add(yyvsp[-3].string, 1);
                                ;
    break;}
case 87:
#line 408 "src/limbaj.y"
{   
                                        //cout << variableToAssign.varName << " type: "<< variableToAssign.varType << endl;
                                        if(FindToBeModifiedVar(variableToAssign)) {
                                            UpdateArray(modifiedVariable);
                                        }
                                    ;
    break;}
case 88:
#line 415 "src/limbaj.y"
{
                                    //cout << variableToAssign.varName << " type: "<< variableToAssign.varType << endl;
                                    if(FindToBeModifiedVar(variableToAssign)) {
                                        UpdateArray(modifiedVariable);
                                    }
                                ;
    break;}
case 89:
#line 424 "src/limbaj.y"
{ 
                                    checkObject(yyvsp[-2].string, yyvsp[0].string);
                                    variableToAssign.varName = yyvsp[-2].string;
                                    variableToAssign.varType = 2;
                                    variableToAssign.varField = yyvsp[0].string;
                                ;
    break;}
case 90:
#line 431 "src/limbaj.y"
{ 
                                    checkObject(yyvsp[-5].string, yyvsp[-3].string);
                                    variableToAssign.varName = yyvsp[-5].string;
                                    variableToAssign.varType = 2;
                                    variableToAssign.varField = yyvsp[-3].string;
                                    variableToAssign.varIndex[0] = currentArraySizes[0];
                                ;
    break;}
case 91:
#line 439 "src/limbaj.y"
{
                                variableToAssign.varName = yyvsp[0].string;
                                variableToAssign.varType = 0;
                          ;
    break;}
case 92:
#line 444 "src/limbaj.y"
{
                                exists_or_add(yyvsp[0].string, 0);
                                variableToAssign.varName = yyvsp[0].string;
                                variableToAssign.varType = 0;
                                ;
    break;}
case 93:
#line 450 "src/limbaj.y"
{
                                    variableToAssign.varName = yyvsp[-3].string;
                                    variableToAssign.varType = 1;
                                    variableToAssign.varIndex[0] = currentArraySizes[0];
                                ;
    break;}
case 94:
#line 459 "src/limbaj.y"
{
                                checkFunction(yyvsp[-3].string);
                                currentCallList.clear();
                            ;
    break;}
case 95:
#line 464 "src/limbaj.y"
{
                                checkFunction(yyvsp[-2].string);
                                currentCallList.clear();
                           ;
    break;}
case 96:
#line 468 "src/limbaj.y"
{runPrint();
    break;}
case 97:
#line 469 "src/limbaj.y"
{runTypeOf();
    break;}
case 98:
#line 473 "src/limbaj.y"
{
                                setCurrentClassName(yyvsp[-5].string);
                                checkMethod(yyvsp[-3].string);
                                currentCallList.clear();
                            ;
    break;}
case 99:
#line 479 "src/limbaj.y"
{
                                setCurrentClassName(yyvsp[-4].string);
                                checkMethod(yyvsp[-2].string);
                            ;
    break;}
case 100:
#line 487 "src/limbaj.y"
{ 
                                currentCallList.push_back(currentVariable);
                                stiva.pop_back();
                          ;
    break;}
case 101:
#line 492 "src/limbaj.y"
{                                
                                currentCallList.push_back(currentVariable);
                                stiva.pop_back();
                          ;
    break;}
case 102:
#line 499 "src/limbaj.y"
{Operation_on_stack(BAND);;
    break;}
case 103:
#line 500 "src/limbaj.y"
{Operation_on_stack(BAND);;
    break;}
case 104:
#line 501 "src/limbaj.y"
{Operation_on_stack(BOR);;
    break;}
case 105:
#line 502 "src/limbaj.y"
{Operation_on_stack(BOR);;
    break;}
case 106:
#line 503 "src/limbaj.y"
{
                                                                    expr1 = stiva.back();
                                                                    stiva.pop_back();
                                                                    stiva.push_back(new ASTNode(BNOT, expr1));
                                                                ;
    break;}
case 107:
#line 508 "src/limbaj.y"
{
                                                                    expr1 = stiva.back();
                                                                    stiva.pop_back();
                                                                    stiva.push_back(new ASTNode(BNOT, expr1));
                                                                ;
    break;}
case 109:
#line 516 "src/limbaj.y"
{Operation_on_stack(BEQ);;
    break;}
case 110:
#line 517 "src/limbaj.y"
{Operation_on_stack(BEQ);;
    break;}
case 111:
#line 518 "src/limbaj.y"
{Operation_on_stack(BNEQ);;
    break;}
case 112:
#line 519 "src/limbaj.y"
{Operation_on_stack(BNEQ);;
    break;}
case 113:
#line 520 "src/limbaj.y"
{Operation_on_stack(BGT);;
    break;}
case 114:
#line 521 "src/limbaj.y"
{Operation_on_stack(BGT);;
    break;}
case 115:
#line 522 "src/limbaj.y"
{Operation_on_stack(BGTE);;
    break;}
case 116:
#line 523 "src/limbaj.y"
{Operation_on_stack(BGTE);;
    break;}
case 117:
#line 524 "src/limbaj.y"
{Operation_on_stack(BLT);;
    break;}
case 118:
#line 525 "src/limbaj.y"
{Operation_on_stack(BLT);;
    break;}
case 119:
#line 526 "src/limbaj.y"
{Operation_on_stack(BLTE);;
    break;}
case 120:
#line 527 "src/limbaj.y"
{Operation_on_stack(BLTE);;
    break;}
case 125:
#line 535 "src/limbaj.y"
{
                                setCurrentVariableType(yyvsp[0].string);
                                variableFromExpr.varName = yyvsp[0].string;
                                variableFromExpr.varType = 0;
                                PushVariableToStack();
                          ;
    break;}
case 126:
#line 542 "src/limbaj.y"
{
                                currentVariable.type.typeName = 0;
                                stiva.push_back(new ASTNode(yyvsp[0].number));
                          ;
    break;}
case 127:
#line 547 "src/limbaj.y"
{
                                currentVariable.type.typeName = 1;
                                stiva.push_back(new ASTNode(yyvsp[0].real_number));
                          ;
    break;}
case 128:
#line 552 "src/limbaj.y"
{
                                currentVariable.type.typeName = 2;
                                stiva.push_back(new ASTNode(yyvsp[0].caracter))
                          ;
    break;}
case 129:
#line 557 "src/limbaj.y"
{
                                currentVariable.type.typeName = 3;
                                stiva.push_back(new ASTNode(yyvsp[0].true_or_false));
                          ;
    break;}
case 130:
#line 562 "src/limbaj.y"
{
                                currentVariable.type.typeName = 4;
                                stiva.push_back(new ASTNode(yyvsp[0].string))
                          ;
    break;}
case 131:
#line 567 "src/limbaj.y"
{
                                setCurrentVariableType(yyvsp[-3].string);
                                variableFromExpr.varName = yyvsp[-3].string;
                                variableFromExpr.varType = 1;
                                variableFromExpr.varIndex[0] = currentArraySizes[0];
                                PushVariableToStack();
                          ;
    break;}
case 132:
#line 574 "src/limbaj.y"
{
                                setObjectMemberReturnType(yyvsp[-2].string, yyvsp[0].string);
                                currentVariable.type.typeName = objectMemberReturnType;
                                variableFromExpr.varName = yyvsp[-2].string;
                                variableFromExpr.varType = 2;
                                variableFromExpr.varField = yyvsp[0].string;
                                PushVariableToStack();

                          ;
    break;}
case 133:
#line 583 "src/limbaj.y"
{
                                currentVariable.type.typeName = functionReturnType;
                                stiva.push_back(new ASTNode(0, functionReturnType));
                          ;
    break;}
case 134:
#line 587 "src/limbaj.y"
{
                                currentVariable.type.typeName = functionReturnType;
                                stiva.push_back(new ASTNode(0, functionReturnType));
                          ;
    break;}
case 135:
#line 594 "src/limbaj.y"
{Operation_on_stack(ADD);;
    break;}
case 136:
#line 595 "src/limbaj.y"
{Operation_on_stack(MUL);;
    break;}
case 137:
#line 596 "src/limbaj.y"
{Operation_on_stack(DIV);;
    break;}
case 138:
#line 597 "src/limbaj.y"
{Operation_on_stack(SUB);;
    break;}
case 139:
#line 598 "src/limbaj.y"
{Operation_on_stack(MOD);;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 602 "src/limbaj.y"

void yyerror(const char * s)
{
     cout << "Eroare: " << s << " la linia: " << yylineno << endl;
}

int main(int argc, char** argv) 
{
    #ifdef YYDEBUG
    yydebug = 1;
    #endif
    yyin = fopen(argv[1], "r");
    //current = new SymTable("global");
    //tables.push_back(current);
    yyparse();

    //std::cout << "Variables in global scope:" << std::endl;
    
    for(auto table : tables) 
    {
        table->printTable("scopes/scope.txt");
    }
    
    // Eliberare memorie pentru toate tabelele
    for (SymTable* table : tables) 
    {
        delete table;
    }

    if (errorCount > 0) 
    {
        std::cout << "Aveți " << errorCount << " erori." << std::endl;
    } else 
    {
        std::cout << printToScreen << endl;
        std::cout << "Progrămelul este corect! Bravo!!!" << std::endl;
    }

    return 0;
}
